### ISSUE TITLE
Patcher environment creation failed with the following error: Could not find game folder automatically

### ISSUE THREAD

**Issue by topcheese** [Synthesis-Collective/SynthEBD#10]
Hi, I'm new to all this patcher stuff with Mutagen based patching.  I've played around with the EBD setup in the past.  I just went through setting up a fresh setup.  I'm at a loss here?

**Comment by topcheese** [comment]
I thought that might be it, but I just did the clean game start, and the same problem.  It's probably an anti-virus thing, but it should be fine with the other tools.

**Comment by Piranha91** [comment]
Sorry for the late response! Which game version are you trying to run this for? The patcher starts by assuming SSE and, if unavailable, is supposed to check all other versions (LE, VR, Enderal) but I haven't actually tested on a PC that doesn't have SSE installed. If it is SSE, do you have it installed in a non-default location (e.g. not in your Steam library)?

**Comment by Piranha91** [comment]
Thanks! Just to clarify, you don't have SSE or SLE installed at all? Or just not in the Steamapps folder?

**Comment by topcheese** [comment]
No SSE or SLE. I do have some folders setup for one of the other tools, and
I'm looking into that now.  I don't have those installed, but I do have
some directories setup.

<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=icon>
Virus-free.
www.avast.com
<https://www.avast.com/sig-email?utm_medium=email&utm_source=link&utm_campaign=sig-email&utm_content=webmail&utm_term=link>
<#DAB4FAD8-2DD7-40BB-A1B8-4E2AA1F9FDF2>

**Comment by Piranha91** [comment]
Ok, this is next on my troubleshooting list. I'll touch base in a day or two. Thanks!

**Comment by Piranha91** [comment]
Should be fixed in 0.6. Please reopen as a new issue if it still fails for you. Thanks for the report!
