### ISSUE TITLE
In-game configuration?

### ISSUE THREAD

**Issue by roysorlie** [Synthesis-Collective/SynthEBD#100]
Hi :)

Is there an in-game configuration tool to modify NPC's like the old EBD had?

Again, amazing work!

Cheers

**Comment by Piranha91** [comment]
Thanks! No in game config tool at the moment; Papyrus is not my forte. Might come in a later version, or if someone wants to make an add on, permissions are open. I don’t have the bandwidth for it at the moment unfortunately.

**Comment by roysorlie** [comment]
Thanks for the feedback :)
