### ISSUE TITLE
Notes are erased if subgroup is moved

### ISSUE THREAD

**Issue by ghost** [Synthesis-Collective/SynthEBD#101]
Hey Piranha, a quick bug before I forget... moving a subgroup anywhere (drag and drop) erases the subgroup's Notes field 👀

**Comment by Piranha91** [comment]
Thanks! Fixed on my end, will include in the next release. Is this an urgent problem for you, or do I have time to collect other bugs before pushing?

**Comment by leonardovcr** [comment]
It's really not a big deal, I just had to fix a few notes here and there, but it's already done. Thanks!

**Comment by leonardovcr** [comment]
Just a heads up, still not working on 0.9.6.1 :(

https://imgur.com/a/iIMV7YA

**Comment by Piranha91** [comment]
Wow, low probability event: turns out there were two completely independent bugs that caused this behavior in different contexts. Should be fixed in 0.9.6.3.

**Comment by leonardovcr** [comment]
Fixed, thanks!
