### ISSUE TITLE
Strange/inconsistent AutoBody & refit behavior

### ISSUE THREAD

**Issue by Gawdzila** [Synthesis-Collective/SynthEBD#109]
I'm gonna apologize in advance for this one because it is not extremely reproduceable and happens/behaves somewhat inconsistently -- obviously exactly what you don't want in a problem.  Also because this will be a long post on account of pictures, but hopefully that will make things easier to follow and understand.  Lastly, this is not something that cropped up recently, as I've had similar issues since I started using SynthEBD so it may very well be something internal to AutoBody that you haven't touched, or even something internal to Skyrim.

If this isn't feasible to address or test then that's cool; this tool works well the vast majority of the time, and the bodies change and behave as expected.  Buuuuuuut... I figure if if there's anywhere I can get direction or a fix for my niche little problem, it's here :)

What first led me here was the behavior of worn clothing.  I was at the Thalmor Embassy party with my (mod-added) follower and she looked like this:
![Thalmor Party](https://user-images.githubusercontent.com/119834693/222930531-f2a168d9-cd64-4280-ba09-456d3f12b1e3.jpg)

...and then all of a sudden, I reloaded a save (no changes to patch or bodyslide or outfit), and she looked like this:
![Thalmor Party Squish](https://user-images.githubusercontent.com/119834693/222930538-74db3b7a-24ea-4931-aaeb-da9debf1a476.jpg)

If I removed the dress, her body looked normal:
![Daegon Daedra Body](https://user-images.githubusercontent.com/119834693/222930551-968adb67-41bc-485f-98ac-638b911133d3.jpg)

At first I suspected physics weirdness, but neither re-equipping, changing clothes (the weird shape carried over to other outfits as well), nor disabling physics altogether helped.  You can see her AutoBody Bodyslide selection:
![Daegon Daedra Body AB Window](https://user-images.githubusercontent.com/119834693/222930563-e1685b6f-d12f-4550-81e7-929f084a0bae.jpg)

So I tried patching her to a much different Bodyslide, to see if things would maybe "reset" somehow.  Her body did appear to change (although there is some hint of the chest-area "squishing" I saw with the other body -- Refit problem maybe?):
![Daegon Strawberry](https://user-images.githubusercontent.com/119834693/222930603-b366205f-225d-4c9c-ac21-751827175fe4.jpg)

However, if I remove the dress then she still has her previous body, even as the AutoBody window shows otherwise:
![Daegon Not Strawberry](https://user-images.githubusercontent.com/119834693/222931101-f9416482-5457-49e9-95fa-bc26e8a1661e.jpg)

... and re-equipping adheres the dress to her displayed body rather than the AutoBody-selected one (again with the squished boobs):
![Daegon Not Strawberry 2](https://user-images.githubusercontent.com/119834693/222930618-04681531-e9bc-4d50-a299-f364c2332220.jpg)

At this point I selected her in console and did a disable-enable.  At first things didn't seem to change, but after I removed the dress the body has changed to the AutoBody selection.  You can see that her gloves still are fitting the other/wrong body:
![Daegon Now Strawberry](https://user-images.githubusercontent.com/119834693/222931108-4d4a1abd-7d8d-4c65-ad02-aeea9fe88fd8.jpg)

Once everything is re-equipped she goes back to normal with the new body (albeit still squished up top, which is what I was originally trying to get rid of :-/):
![Daegon Now Strawberry 2](https://user-images.githubusercontent.com/119834693/222930625-ee2bd388-d609-425b-a6b6-300ec02ec9d4.jpg)

Soooo.... after all that, any ideas why AutoBody and the refitting on the dress is behaving this way?  Is this expected behavior from AB that simply carried over?  Is the body swapping behavior just due to the way Skyrim handles saves?  Does this sort of thing happen to anyone else, or is it some weird mod interaction on my end?  Or is this just an unusual problem that might be fixed, either on my end or internally?

**Comment by Piranha91** [comment]
I’m not going to be able to look closely into this for another week or more, but a couple quick things that come to mind:

1) there was some discussion here about deleting refit sliders. Not sure if that would help but figured I’d call it to your attention. https://github.com/Synthesis-Collective/SynthEBD/issues/20

2) this may be more than what you’re willing to do to troubleshoot, but would the same issue occur with OBody NG?

**Comment by leonardovcr** [comment]
Hi, just to drop my 2 cents, try switching to OBodyNG, it's newer and better maintained. I've always had weird issues with AutoBody (like in-game menu not working as expected), and switching to OBodyNG fixed everything.

**Comment by Gawdzila** [comment]
Thank you for the pointers!  If I thought I could use OBody I would have been doing so already, but I was always under the impression that OBody didn't work with VR, even the Standalone version, because it still required the original OBody to work.  But I don't think I had run across NG before... the mod description says

"_OBody NG (Next Generation) is a new version and a replacement of OBody compiled with CommonLibSSE NG - in other words, it means it works with every current Skyrim version, whether it is SE or AE_"

...so, no mention of VR -- but the CommonLibSSE NG Github says

"_CommonLibSSE NG has support for Skyrim SE, AE, and VR, and is able to create builds for any combination of these runtimes, including all three. This makes it possible to create SKSE plugins with a single DLL that works in any Skyrim runtime_".

Does that mean OBodyNG is compatible with VR??  If so, OMG, amazing!  Gonna try and make the migration and test it out right now.  Thanks guys!

**Comment by Piranha91** [comment]
Yup, unless I misremember from my testing, NG did work for me in VR. Make sure your VR address library is up to date.

**Comment by Piranha91** [comment]
In general the NG mods are a mixed bag in terms of VR support, so check the descriptions and comments.

**Comment by Gawdzila** [comment]
Thanks guys, I have OBody NG up and running!  At first I was having problems with presets not applying unless I did a disable/enable or restarting the game, but I found out on the mod page that it was an issue with the Engine Fixes memory manager, so once I disabled that everything seems to work great.  I suspect that may have been the issue with AutoBody, too, but OBody is better and more current anyhow so I'm happy to have switched.  Now I actually have a list of presets when I click on an NPC! AutoBody would only ever list the one they had been assigned, so I would need to re-run the patcher or edit the .ini to change them.

The one thing is that I occasionally find an NPC where OBody shows their preset as Unknown, but I seem to be able to change their preset anyway, so it isn't really a big problem.

I do have one question/suggestion, though.
When you switch an NPC's body in the OBody editing window, I presume it changes their body shape in the .json file in order to remember it.  But does SynthEBD ever read that file, or does it only write it?  In other words, would it be possible to update consistency and/or specific assignments from that .json file?  It doesn't SEEM like this happens currently, and I was thinking it might be a nice easy way to keep from losing any customization we make if there were a button or toggle or some other option.

**Comment by Piranha91** [comment]
Is it true that OBody writes its assignments to a json file rather than keeping them in memory? If so, I should be able to read it in and synchronize. Can you point me to the file?

Btw, for my own future reference when I finally play (lol), what was the issue with Engine Fixes?

**Comment by Gawdzila** [comment]
Ahh, sorry, false alarm.  OBody said in the description that "OBody NG has more customization options, and its JSON file is more powerful and more user friendly than AutoBody's ini file" (I thought they meant the morphs.ini file) and there is also a file called "OBody_presetDistributionConfig.json".  Buuuuut it turns out when I open it up that it is just the blacklists rather than the body distribution.  Bummer.

As for Engine Fixes, let me serve up some copypasta from the FAQ:


> 9) Everything works but the bodies don't change when I choose a preset on the OBody preset list, or the presets stop applying randomly after some time has passed, or changing the character's weight won't change the body size.
> 
> This is a memorisation issue with SSE Engine Fixes and Racemenu. The preset and weight changes will only apply if the actor redresses, if you change cells or if you save the game, exit the game and reload the game.
> 
> You can also reproduce this by opening the console, type showracemenu, and try to edit the CBBE or UNP morphs. You will see that your character's body will not change.
> 
> To fix this, set MemoryManager and ScaleformAllocator to false in the SSE Engine Fixes configuration found in SKSE > Plugins > EngineFixes.toml, wherever you installed SSE Engine Fixes to. NOTE HOWEVER that turning those two off might cause CTDs in load orders with many mods.
> ...
> This problem also exists in Autobody, and is well documented in both Racemenu's and Autobody's Github repositories.


I will also say, in my version of Engine Fixes (I have the latest version, I checked), it did not have the exact settings in the exact places described.  The .toml file doesn't seem to have any manual settings, but the .ini file contains a line for "MemoryManager = true", which I changed to false.  I also didn't find a Scaleform Allocator setting at all, but there is a "FormCaching = true" setting that I also changed to false.  I'm not sure that it's the same thing, but I figured it couldn't hurt since it is apparently of questionable usefulness anyway.

**Comment by Piranha91** [comment]
Closed due to inactivity.
