### ISSUE TITLE
Cannot launch patcher with MO2 stock game folder

### ISSUE THREAD

**Issue by antoshayastreb** [Synthesis-Collective/SynthEBD#11]
Hello, i'm using modlist from Wabbajack and assuming that mo2 points game files to stock game folder. When i press run, logs showing me many errors listed below.

![Снимок экрана 2022-04-29 015511](https://user-images.githubusercontent.com/34381227/165860998-4ae631c8-eec8-4643-bdad-6bf87c296bfd.png)

I tried to change mod folder location in settings to stock game folder, but no luck. Is there any options i missed?

![Снимок экрана 2022-04-29 015707](https://user-images.githubusercontent.com/34381227/165861407-f923e648-bde0-4663-a467-2e548b0a9723.png)

**Comment by Piranha91** [comment]
The Mod folder path should not point to the stock game folder. It should be D:\Gmaes\MO2Skyrim\mods.

When you were installing config files, did you do it via the archive installer (first option) or Install from JSON (second option)? If the first option, did you remember to activate the newly created mods in the left panel of MO2? If from JSON, did you manually extract the expected assets into a new mod folder?

**Comment by antoshayastreb** [comment]
I installed config files via the archive installer and actived mods in mo2. For the first try mod folder path was poined to mo2 mods folder and still there were errors 'No file exists'.

**Comment by Piranha91** [comment]
Is your Skyrim installed outside of your steam library? I am actually actively working on releasing beta 0.7 with support for installations outside of the steam library - will hopefully release by tomorrow, if not then definitely over the weekend.

**Comment by antoshayastreb** [comment]
Just checked the paths and still no luck.
No, skyrim installed in the steam library, think i will wait for the next release than. 
Thank you for your time and hard work:)

**Comment by Piranha91** [comment]
I appreciate it! From the errors it's not necessarily an environment/game folder issue. If you only select "patch heights" in the main menu, does it produce an output file? You're launching SynthEBD through MO2 right? If environment creation is working, the only obvious reason I can think of for why you would see those errors is if you were launching SynthEBD outside of MO2.

**Comment by antoshayastreb** [comment]
![image](https://user-images.githubusercontent.com/34381227/165903244-1ec4f5d2-71fd-4ca6-bdd3-0e8ef2513917.png)
![image](https://user-images.githubusercontent.com/34381227/165903343-0b8a555c-3e32-4838-a1b7-aa900328d11d.png)
![image](https://user-images.githubusercontent.com/34381227/165903364-7611bc75-a8d5-4200-8586-ba43da25bf2d.png)
Doesn't work either if i understand you correctly, mo2 overwrite is empty too.
