### ISSUE TITLE
Logging suggestions/issues

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#114]
Hey Piranha, I've been trying to figure out why some NPCs aren't being patched, and have come across some logging issues which I think could use some improvement.

While testing your Male Tempered Skins config file, I've noticed that according to that final log statistics message, Imperial and Nord Male Vampires aren't being 100% patched. This is in contrast to my BnP Male config file, which patches 100%. That makes me think that maybe some rules or custom tweaks I did might need some adjustments...

In order to track this down, I enabled "Verbose Mode for Conflict NPCs", but I'm getting TONS of log files being generated to NPCs which, from what I could check, are indeed being correctly patched... I suspect that the patcher is considering any failed MixIn distribution as a conflict. I understand that a failed Primary Asset assignment should indeed generate a conflict log file, but I'm not so sure about the need for that for MixIn assignments, since some really shouldn't be assigned due to probability or missing rules. Here are some conflict npcs log examples:

[npc_logs.zip](https://github.com/Synthesis-Collective/SynthEBD/files/11044371/npc_logs.zip)

That being said, do you have any suggestions on how I should try to track these conflicting npcs? 

Maybe adding a new log option to always log based on an NPC attribute like Race could be heplful. This way I could set logging for all Imperial and Nord Race vampires and check what's going on. Another solution would be an option to not have the patcher consider a failed MixIn assignment as a cadidate for conflict logging, or just disregard that as a conflict in order to not clutter the log directory... what do you think?

**Comment by Piranha91** [comment]
Yeah mix ins shouldn’t be considered conflicts, can definitely fix that. How would you feel about a “subgroup-like” interface for logging criteria?

**Comment by leonardovcr** [comment]
I was thinking of an interface which lets you choose multiple criteria just like those available on Attribute Groups creation. If the subgroup-like approach can replicate that flexibility, then sure, would be very helpful!

**Comment by Piranha91** [comment]
Implemented in 0.9.9.2 - hope it's satisfactory.

**Comment by leonardovcr** [comment]
Thanks, debugging is much easier now. I'm still getting tons of conficts related to bodyslides not matching rules, which I'm still trying to debug where the problem could be. Will let you know if I find something more concrete...

**Comment by Piranha91** [comment]
Thanks! I’ll try to take a look at bodyslide logging in the next day or two and see if I find any other false triggers.

**Comment by leonardovcr** [comment]
Found out the reason for the bodyslide conflicts, I somehow managed to mess up one of my bodyslide descriptor rules. Was probably tinkering and forgot to fix 🤦 I think we can close this issue, everything seems in order :) thanks!
