### ISSUE TITLE
Face discoloration when equip npc item

### ISSUE THREAD

**Issue by lolbleach001** [Synthesis-Collective/SynthEBD#116]
Discoloration face when equip item in npc. enabled ebd scripts and blocked mods head parts and didn't fix it

**Comment by Piranha91** [comment]
How are you equipping items to NPCs? Is it all items, or a specific item or type?

**Comment by lolbleach001** [comment]
Outfit NPCs (Inventory-Equipment) SE. There are also moments where the game loads and the color of the face also changes

**Comment by lolbleach001** [comment]
any solution?

**Comment by lolbleach001** [comment]
> Outfit NPCs (Inventory-Equipment) SE. There are also moments where the game loads and the color of the face also changes

**Comment by Piranha91** [comment]
If you update to 1.0.0.2 using a clean save, does the issue still occur?

**Comment by Piranha91** [comment]
This issue should be resolved in version 1.0.0.3 (requires a clean save, or new game). Thanks for providing the mod to reproduce it.

**Comment by Piranha91** [comment]
Closed due to inactivity.
