### ISSUE TITLE
SynthEBD has crashed with error 

### ISSUE THREAD

**Issue by Gerkesiz** [Synthesis-Collective/SynthEBD#128]
Log : https://pastebin.com/f0vcsXYk

I installed the program a few weeks ago and was able to launch it without errors. . But I took a break from modding for a few weeks. When I started modding again, I realized that the program was not working.

Edit: I installed the program, made the settings in the videos and left. So I haven't started using it yet. I downloaded the skin mods along with the config files and took a break from modding.

**Comment by Piranha91** [comment]
Same answer here as on the Nexus- try updating to the latest version of SynthEBD.
