### ISSUE TITLE
The torso paths for all assets are wrong.

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#13]
It may be my environment, but no matter which Assets I use and install, the torso path is vanilla. 
I tried with v4.0 v5.1 v6.0 men and women, BIJIN DEMO TEMPERD VITRUVIA, but only the torso path was vanilla in all cases.

AND V6.0 cannot adding specific NPC assignment cuz crash.

https://user-images.githubusercontent.com/100354903/167257445-f81552a3-2ef9-4738-b581-753affbafdc1.mp4

)

**Comment by Piranha91** [comment]
Can you please let me know if the issue happens in this version? https://drive.google.com/file/d/1P06bZ92YByigMy3klIzVLWI4LY8YLpko/view

**Comment by Daikichi-Takahey** [comment]
It just works. Thx nice works

But another problem ,TSM sos light version feet texture path is wrong. Vitruvia works
![スクリーンショット (37)](https://user-images.githubusercontent.com/100354903/167298109-fbe752bd-24db-4aec-b965-06d097911cfa.png)
