### ISSUE TITLE
Autobody NPC Group Sub-Attribute reverting between sessions

### ISSUE THREAD

**Issue by zhaobenny** [Synthesis-Collective/SynthEBD#16]
The checkboxes in the Group sub-attribute for Autobody presets are being reset after I close SynthEBD.

What I see after I open the program again:
![image](https://user-images.githubusercontent.com/46238123/170575861-a97329d0-6187-40ac-baf7-210a6923300e.png)

**Comment by Piranha91** [comment]
I am able to reproduce the issue. Thank you for the report. I'll be travelling this weekend but will prioritize it when I return (possibly during if I can squeeze in the time).

**Comment by zhaobenny** [comment]
Thanks, looks like it works fine now! 👍
