### ISSUE TITLE
Massive memory usage

### ISSUE THREAD

**Issue by HitBug83** [Synthesis-Collective/SynthEBD#25]
I've got a big memory drop when I click on a subgroup containing a lot of texture files (like Mature Skin Body/Head Diffuse for example). I have a custom config with even more texture options and I've got quickly 100% memory usage if I click on the wrong place (and most of time a crash). I've tried to disable "Show preview image" but it is still loading a lot of data, more than the size of all the texture files in the subgroup.

Edit : 8GB RAM (almost 6GB free on startup)

**Comment by Piranha91** [comment]
Could you possibly share the custom config that causes you to crash? I've never noticed this memory usage issue on my end. That said, right now IIRC the images are always loaded and the checkbox only controls if they are displayed or not - I could look into changing this so the box actually controls image file loading.

**Comment by Noggog** [comment]
Got a few patterns that would help keep only one image loaded in at a time, or at least delayed until they're focused.   Shoot me a message if you want a brainstorm

**Comment by Piranha91** [comment]
Quick question, HitBug83. Do you see the 100% memory usage all at once when you load SynthEBD, or does it keep accumulating as you click through subgroups?

**Comment by HitBug83** [comment]
It occurs only when I click on a subgroup in the texture customization tab. The memory usage spike is higher with the subgroups containing a lot of textures, like the main "Head Diffuse" or "Body Diffuse" of the Mature Skin config you provided (unmodified). If I click on a lighter subgroup afterward, like Hand Specular for exemple, I get most of my memory back after 10 seconds or so. It is apparently directly related with the global size of the folders the subgroups are pointing to.

If I switch from a heavy subgroup to another without waiting, the memory usage is so high that  I cant even control the mouse and most of time it crashes. Sometimes I get a crash report message  mentioning .dds files.

I can share the main config file I'm working on but since I'm using a custom texture folders architecture, I'm not sure it would be helpful without the texture files. Again, I have the issue even with the config files you provide. Let me know if you still want it, I'll share it when I will be back from work.

**Comment by HitBug83** [comment]
Here is what is happening with your unmodified Mature Skin Body Diffuse subgroup.

It's even worse with my custom config containing a lot more skins, I have to avoid all main branch subgroups or be very quick with my edits otherwise I loose control and it ends with a crash (sometimes SynthEBD stays alive and give me a crash message, sometimes it's full CTD). 


https://user-images.githubusercontent.com/109113269/178555848-bfc58433-79ea-4d40-ba8f-eaf61b5a7050.mp4

**Comment by Piranha91** [comment]
Can you try this build and let me know if it resolves the memory issues at all (either with or without the "Display Image Preview" toggled? https://drive.google.com/file/d/1wr3q0r9F1JMF0Hx1QYxRIY5VA7HyBHPn/view?usp=sharing

**Comment by HitBug83** [comment]
So, without the "Display Image Preview", no memory usage spike, awesome.

But with the Preview enabled, I still have the issue.

If I disable the preview while it is loading textures BEFORE 100% usage, it calms down and I get my memory back. But if I reach 100%, even if I disable it, the memory usage stays very high, as if it does not manage to empty the data.

Another thing maybe worth to consider : I did my testing mostly on the two heaviest config files I have, because others were fine with 0.7.6 (well, unless if I jumped from subgroup to subgroup like crazy...). Those two config files are your Mature Skin HD (data folder size = 1,62 GB) and my custom insane config mixing a ton of different texture mods (data folder size = 12,5 GB). Despite of the massive data load on my custom config, the slope of the memory usage graph is far steepest with the Mature Skin config. I reach 100% in less than 10 seconds with Mature Skins (as you saw in the video above), and maybe in 30 seconds with my config. The main difference between the two is the size of each texture individually : 8K with Mature Skins and 4K with most of my custom config files. So it seems that SynthEBD handles better a lot of smaller files than fewer bigger files.

As for the subgroup disappearance, it still happens, with or without preview.

**Comment by Piranha91** [comment]
I've implemented several behaviors to manage this in 0.7.71, including rearranging the UI to only display 1-2 config files at a time, limiting the size of the preview images (user-customizable) and halting preview image loading when the computer is near its memory limit. Please let me know if this is sufficient to allow you to load your large config file.

**Comment by Piranha91** [comment]
Does this happen every time you switch, or only if you switch in rapid
succession?

**Comment by HitBug83** [comment]
From what I've seen, it happens only when there is a lot of assets in a subgroup.

If I switch from a subgroup with just one asset, I don't think the preview of this asset ever stayed displayed after the switch.

But with a switch from a subgroup with many assets (like one of the main head/body/hands), many previews from the previous subgroup are displayed in the next one. It looks like they stay in a queue and are still loaded even if they should not anymore.

**Comment by Piranha91** [comment]
v0.7.7.2 should take care of this last issue - if it doesn't I'll need to rethink my loading strategy entirely.

**Comment by HitBug83** [comment]
It does ! Thank you.

No more unwanted previews when switching suggroups, and far less processing meaning better performances when tweaking big config files.
