### ISSUE TITLE
All NPCs are matching ForceIf attribute

### ISSUE THREAD

**Issue by HitBug83** [Synthesis-Collective/SynthEBD#27]
Hello,

I have some weird results with the new Force If and Force if and Restrict results.

A lot of NPC are not getting valid combination at all, and those who get one are all getting a "Forced If" skin even if they should not.

According to the verbose mode log, if I set a Force If attribute, all NPCs I checked (a dozen at random) are said matching the attribute where they should not. This leads to a lot of broken scenarii where most of them are left without any valid combination.

For example, if I try to set all beggars dirty, I pick a dirty skin and I add Class = Beggar in the Allowed NPC attribute box, then I choose Force if and restrict. I run the patcher and all the non-beggars NPCs I check have this line in the verbose log :  

Current NPC matches the following forced attributes: 	{Class: [Beggar]} (Weighting: 1)

Did I miss something ?

**Comment by Piranha91** [comment]
Apologies, you most likely are not missing anything. I was in a rush to get the other bug fixes to 0.7.5 out and I only briefly tested the new ForceIf implementation - I knew upon release that I should have tested in more detail but, well… anyway, I finally have some time tomorrow to sit down and code, and I’ll make looking into this my first priority. Thanks for the report.

**Comment by Piranha91** [comment]
I just released v0.7.6.1 which should fix this issue. I did some basic testing and attributes behaved correctly, so I think the function works now, but I'm away from my desktop for the next 4 days and my laptop is very slow which makes coding and testing painful, so I'd appreciate your feedback on the new version if you get a chance. 

BTW, I've also been able to replicate the disappearing subgroup issue you reported on my laptop. The fact that it doesn't happen on my desktop suggests it might be a performance issue of some sort. I have no clue what might be causing it, but I'm planning to rework the UI a bit anyway so hopefully it'll fix it. I'll keep you posted.

**Comment by HitBug83** [comment]
I did some testing and so far everything is working great ! Me and my dirty beggars thank you.

You can also close issue #24 because both issues were fixed by your update.

Concerning the disappearing issue, you should probably start by disabling texture loading and see if it happens again. As far as I can tell, the more textures are in a subgroup, the more it is likely to disappear.
