### ISSUE TITLE
GUI issue in Allowed BodySlide Descriptors

### ISSUE THREAD

**Issue by izomiac** [Synthesis-Collective/SynthEBD#31]
In 0.7.7.1 I tried to change the allowed bodyslide descriptors for my asset packs, since they don't get saved (a bug in its own right I suppose), and realized I couldn't use the chest category.  The window jerks for a second and stays on body.  Subsequent testing shows that clicking and dragging down works, which is probably because the box moves down when I activate that category.  Similarly, going back to body requires me to click and drag up, probably because the box is higher up when I have that category selected.

**Comment by Piranha91** [comment]
Any chance you can share a screen capture of the issue, and provide the config file? I can't replicate this on my end - I can switch the active category for the allowed bodyslide descriptors, and whichever ones I toggle are saved when the config file saves.

**Comment by izomiac** [comment]
No problem.  In the screen capture I try normal clicks a few times, before click and dragging.  I was hesitant to report the saving issue since I'm not 100% sure I'm using that feature correctly, but both apply to the same option so I figured I'd mention it.  These config files normally live in my Skyrim Data folder (technically a MO2 mod).

![Screen Capture](https://user-images.githubusercontent.com/6551261/180138375-242628cd-a2c1-4332-90b1-66a56cf2cd93.gif)

[SynthEBD Config.zip](https://github.com/Synthesis-Collective/SynthEBD/files/9156452/SynthEBD.Config.zip)

**Comment by Piranha91** [comment]
Got it! Sorry, didn't realize you were talking about the whole-config distribution rules rather than subgroup distr rules. Am able to replicate, will take a look. Thanks!

**Comment by Piranha91** [comment]
This should be fixed in v0.7.7.2. Please let me know if the issue persists.

**Comment by izomiac** [comment]
It's fixed, thanks!
