### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by theemptycastle** [Synthesis-Collective/SynthEBD#32]
Somewhat similar to issue 25, though different enough to warrant its own report I think.

Version 7.8.1

Observed behavior: When adding or removing Race Groupings in General Settings, an abnormal amount of memory is being allocated, seemingly exponentially per group added/removed.

Adding a new empty group RAM usage:
1 new group: from 434 MB to 443 MB (9 MB diff).
2: 443 > 473 (30 MB)
3: 473 > 561 (88 MB)
4: 561 > 719 (158 MB)
5: 719 > 1080 (361 MB)
6: 1080 > 1824 (744 MB)
7: 1824 > 3476 (1652 MB)
8: 3476 > 7053 (3577 MB) (from here SynthEBD noticeably stops responding until the new limit is reached)
9: 7053 > 14588 (7535 MB)
10: 14588 > 24105 (9517 MB)
11: maximum possible usage on my system

This also happens when removing groups, I presume adding and removing one group 10 times would produce a similar behavior.

Steps to reproduce: Launch SynthEBD from MO2 > open Race Groupings dropdown in General Settings > click "add group" > observe memory usage in task manager > continue adding groups

**Comment by Piranha91** [comment]
Good catch. When the .exe finishes compiling in a couple mins, could you please check if v0.7.8.2 fixes the issue?

**Comment by theemptycastle** [comment]
Fixed! I created then removed around 15 groups or so, with no noticeable impact on memory usage.
