### ISSUE TITLE
(most likely my fault) Error: Expected and failed to find an object at path

### ISSUE THREAD

**Issue by theemptycastle** [Synthesis-Collective/SynthEBD#33]
See error logs here: [ebderror.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9178127/ebderror.txt)

Unfortunately I'm not exactly sure what the culprit is here, hoping you might be able to discern more than I can from these logs.

I installed a few different NPC mods (Populated Skyrim HELL, Citizens of Tamriel, 3DNPC, and corresponding Modpocalypse packs) and created an unrelated new config in SynthEBD. However even after undoing all the changes I made between the last time I didn't get these errors and now, the issue persists.

Any hint on how I might fix this?

**Comment by Piranha91** [comment]
Did you set your additional record templates as in the screenshot below from the Tempered Skins config file? It looks like it's looking for a Tail record in the main humanoid record template, which doesn't have a tail.

![image](https://user-images.githubusercontent.com/63175798/180717366-9150ce99-7494-4828-9e2f-d8f173d7c4f6.png)

**Comment by theemptycastle** [comment]
Awesome, that wasn't the exact issue but it led me in the right direction. My record templates did look just like the screenshot, but earlier I changed the Whole Config Distribution Rules to disallow Khajiit and Argonians since I'm using the Masculine/Feminine Khajiit/Argonian configs and didn't want them competing with any other config.

Removing the disallowed races from the Tempered Skins config didn't fix the issue, so I can't be sure that was the cause, but deleting all Khajiit/Argonian subgroups did fix the issue.
