### ISSUE TITLE
(not an issue) Is there somewhere to discuss/get help with SynthEBD (discord or github discussion perhaps?)

### ISSUE THREAD

**Issue by theemptycastle** [Synthesis-Collective/SynthEBD#35]
I've been using synthebd for a little over a week now and there's still just a couple peculiarities I've been having trouble with (particularly integration with other NPC overhauls and EasyNPC). Since the issues are most likely user error or not understanding the limitations of the software,  it seems inappropriate to use the issue page to ask for help. It'd be great if there was somewhere we could discuss tangential (non-bug related) stuff.

**Comment by Piranha91** [comment]
As luck would have it, there is! Join the Synthesis Discord (https://discord.gg/Fn4cHzwH) and post in the #spawn-support channel.
