### ISSUE TITLE
Changes to a cloned preset persist on all instances of that preset

### ISSUE THREAD

**Issue by Foroneus** [Synthesis-Collective/SynthEBD#38]
When you click on "clone preset" and attempt to modify that clone, any changes you make will also be made on the original (as in, cloning a preset and then changing the minimum weight on that clone will change the minimum weight on both the clone _and_ the original).

**Comment by Piranha91** [comment]
Thanks for the report. In my testing, it's only the min and max weight that were linked between clones; everything else could be modified independently. Let me know if there are other erroneously linked items that you see. Otherwise, this is fixed in v0.7.8.7.
