### ISSUE TITLE
SynthEBD slowdown with a big consistency file of around 10k npcs

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#41]
So, now I'm running into some issues regarding the consistency file and a large number of patched npcs...

SynthEBD becomes very slow to respond after patching around 10knpcs. There is a significant time lag between the "Finished patching in ..." message and the "Wrote output file at..." message, taking longer than the actual patching process duration. 

I've noticed that after quitting the app, it creates a consistency file (of around 10mb) inside NPC Configuration directory even though I've disabled consistency in general settings. Does it always create that file? If I then start the app again, it takes a looong time to load and start. So much so, that I have to kill the process, delete the consistency file, and then start it up again.

**Comment by Piranha91** [comment]
Yep sorry, I noticed that as well and fixed it on my end but haven't yet made a release - should put one out in a few hours, need to take a break for a bit. It's not actually the size of the consistency file that's the problem (though that exacerabates the issue) - it's some extra processing I had going on for each consistency entry.

**Comment by Piranha91** [comment]
Just made the release - should compile in a few. Should clear the issue.

**Comment by leonardovcr** [comment]
Yeah, v.7.8.9 fixed the slowdowns! Much faster now, thanks :)
