### ISSUE TITLE
Crash message box after press Run

### ISSUE THREAD

**Issue by Inokentych** [Synthesis-Collective/SynthEBD#42]
[2022-08-21-14-51.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9389050/2022-08-21-14-51.txt)
So i partially fix this issue by manually create folder SynthEBD in SynthEBD Output, partially because this way patch process start without that error but then another problem show up, as you can see at this screenshot...
![Synth EBD error](https://user-images.githubusercontent.com/111687742/185790240-b9e5b3ec-d3c8-46f6-bd98-d1b827ded623.png)

**Comment by Piranha91** [comment]
Very strange. You’re sure the output folder exists and is not locked from writing via permissions? Do you have a previous version of SynthEBD.esp in your load order? If so, what happens if you deactivate it? Alternatively, will it let you write if you change the output name to SynthEBD2 in the main menu?

Thanks for the crash report - forgot to run the check for if that folder exists, will fix in the next version.

**Comment by Inokentych** [comment]
> Very strange. You’re sure the output folder exists and is not locked from writing via permissions? Do you have a previous version of SynthEBD.esp in your load order? If so, what happens if you deactivate it? Alternatively, will it let you write if you change the output name to SynthEBD2 in the main menu?
> 
Not sure if my answers still needed but here they: Output folder exist, about lock by permission, i try 2 methods: folder created by mod organizer option "create empty mod" or manually create folder in mods with same result. No, i not have previous version of esp, and change name of generated esp not help.

**Comment by Piranha91** [comment]
I fixed the crash you described in the latest git commit and will package the release later today, but unfortunately I cannot replicate the issue with "Could not write output file" that your screenshot shows. If you have another instance of MO2, could you possibly try installing and running SynthEBD there to make sure it's not an issue with that particular folder?

**Comment by Inokentych** [comment]
i not understand why it can't write i not do anything special about it, all other utilities like wrye bash work and create their esp without problem...

**Comment by Piranha91** [comment]
Have you tried selecting a different output directory as a test?

**Comment by Inokentych** [comment]
> Have you tried selecting a different output directory as a test?

of course tried

**Comment by Inokentych** [comment]
> What happens if you clear the output directory? It should try to go to the overwrite folder.

it wrote esp in folder where SynthEBD installed but only after i manually create SynthEBD folder in it as crash workaround

**Comment by Inokentych** [comment]
Ok, now all good, esp created with proper folder, not sure what it was but i tried to play with win10 settings like enable/disable secure folders option but not sure if it relevant to "can't write" problem, maybe just windows restart do job...
