### ISSUE TITLE
Feet textures mismatch with multiple body normals, diffuse and specular

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#45]
Another bug, which _may_ be related to issue #40 ...

I built an asset pack which has distinct body normals, diffuses and speculars for each one of the main races, and one specific body normal for ElderRace. All paths are fine on SynthEBD, pointing (and previewing) the proper textures for each case. Distribution logs are also fine, following the rules with no problems:

Current Combination: HeadD.DefLip.Bret , HeadN.NE.Old.Bret , HeadX.Main , HeadS.Bret , HeadO.Rough , BodyD.H.Bret , BodyN.NE.H.Bret , BodyX , BodyS.H.Bret , HandD.Bret , HandN.NE.Bret , HandX

However, I noticed that in-game all feet for all races were wrong...
Decided to check on SSEDIT, and found out that most paths for the other IDs are ok (like SkinFemaleTorsoDefault014, Hands, etc), except for the feet ones (like SkinFeetDefault0005, 0004, etc). They are all loading from the default paths and one femaleold path:

TX00 - Diffuse: actors\character\female\femalebody_1.dds
TX01 - Normal/Gloss: actors\character\femaleold\femalebody_1_msn.dds
TX03 - Glow/Detail Map: actors\character\female\femalebody_1_sk.dds
TX07 - Backlight Mask/Specular: actors\character\female\femalebody_1_s.dds

**Comment by Piranha91** [comment]
If you want to send the config file through Google drive, pastebin, etc, I can take a look and see if I find the issue. Alternatively there’s a button to auto-set destination paths. My first troubleshooting recommendation would be to back up your current config file and then try using that function in case any of the destinations are improperly set.

**Comment by leonardovcr** [comment]
It's up on Nexus already: https://www.nexusmods.com/skyrimspecialedition/mods/73717?tab=files
The problem happens only with the female asset pack.

I had the same problem once and the auto-set destination button solved the problem (however, at the time it kind of duplicated the asset paths... don't know why) . I did try the auto-set destination option yesterday, but nothing changed.

**Comment by Piranha91** [comment]
Feet are a bit difficult for the auto-set function because they use the same source textures as body (usually, with the exception of SOSL). I don't have the code in front of me, but from memory, I believe the function checks
- is there a body texture, and only one? if so, duplicate it and assign it to feet
- are there two body textures?  if so, move on.

I should update it to handle feet better.

**Comment by leonardovcr** [comment]
Ah, so that's how it works... thanks for explaining
I'll fix the config files tomorrow and test again, it should run flawless now. Thanks again!
