### ISSUE TITLE
"Auto-set destination paths" button sometimes duplicates entries

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#46]
Another issue I'm running into:

![image](https://user-images.githubusercontent.com/13605450/186197884-879f7f4f-d173-410c-8cb9-52fce0b67a50.png)

Pressing the auto-set destination path button sometimes duplicates asset paths entries. So, if I have 2 fields, it duplicates to 4. Four fields becomes eight, and so on. Also, destination fields are being highlighted with red color, even though they are correct.

**Comment by leonardovcr** [comment]
Just an update, in this case all fields are highlighted red, however, file exists and preview works:

![image](https://user-images.githubusercontent.com/13605450/186202346-8cd4df97-b3b1-4d24-89ae-b78024f45012.png)

**Comment by Piranha91** [comment]
I believe this was fixed in 0.9.0.2. Feel free to reopen if there's still buggy behavior.
