### ISSUE TITLE
Could not write to output file

### ISSUE THREAD

**Issue by Shmeeeps** [Synthesis-Collective/SynthEBD#48]
Finished patching in 00:00:06
Could not write output file to B:\SkyrimShit\SynthEBD_v0.8.1.2\SynthEBD.esp

I'm not sure what's going on, but I stopped usiing synth ebd months ago because it wont write to any output I set. I figured maybe it's just a bug and I'll wait for you to update it, but that's not the case because it still won't work. So obviously I'm doing something wrong on my end. Doesn't matter which drive or which folder I choose, it just gives me the same message after it runs the patcher saying it won't write to any of the outputs.

**Comment by Piranha91** [comment]
There seems to be something going on with “secure folder access” - see this comment and try disabling it? https://github.com/Synthesis-Collective/SynthEBD/issues/42#issuecomment-1223570733

**Comment by Shmeeeps** [comment]
Um, I actually figured it out. I'm just kind of dumb. I wasn't using the texture and meshes feature, only the bodygen and hight gen. so SynthEBD wasn't even creating the SynthEBD.esp, since there was no need for it. I just got confused and assumed nothing was being outputed, but in reality it said the esp couldnt be sent to the output and it made me assume there was an issue with all the files being sent to the output.

**Comment by Piranha91** [comment]
SynthEBD actually needs to create the .esp for BodyGen to work. The BodyGen file needs to be in a directory whose name matches a plugin in your load order - it's expecting SynthEBD.esp. I suppose you could rename the directory to DynDOLOD.esp or some other plugin you have in your load order.
