### ISSUE TITLE
Text replaced with odd symbols

### ISSUE THREAD

**Issue by Inokentych** [Synthesis-Collective/SynthEBD#49]
![SynthEBD wrong localization](https://user-images.githubusercontent.com/111687742/187362027-47749cc1-5db1-4bfe-b5d3-cd5fc72dc7b7.png)
looks like SynthEBD not like non Latin alphabet. Initial language russian, in patch it converted to odd symbols, also in some cases it left blank fields instead text where usually names of NPC or description of races. And this issue more critical than it sound as NPC with blank names become non interactive (speak, steal not work) I only enable option to change textures...

**Comment by Inokentych** [comment]
looks like SynthEBD not like non Latin alphabet. Initial language russian, in patch it converted in odd symbols. I not suru why synthEBD ever touch that records if it business change textures (i only enable option to change textures)...

**Comment by Piranha91** [comment]
To clarify, all English text is replaced by the symbols. or just some fields?

**Comment by Piranha91** [comment]
Try 0.8.1.5. SynthEBD shouldn't touch any of those fields directly, but I see a recent entry in the Mutagen change log regarding language string settings. I updated the Mutagen dependency to the latest version so maybe that will fix it. If not we can dig in deeper.

**Comment by Piranha91** [comment]
Closed due to inactivity - please reopen if there are still issues. I don't have a foreign language version to test on.
