### ISSUE TITLE
How do I make Subgroupe?

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#5]
Please watch the video.
https://user-images.githubusercontent.com/100354903/157262507-4df96c24-f559-48af-b54c-f1cd0b73563f.mp4

**Comment by Piranha91** [comment]
Thank you for the report! You absolutely should be able to add subgroups to a new config file and the code for it is already written; I just forgot to make the button for it in the UI. I'm at work now but will fix tonight. Thanks for letting me know!

**Comment by Piranha91** [comment]
Sorry for the delay! I wanted to fix both issues in the same release. Fixed in v0.4.0. Thanks again for reporting!
