### ISSUE TITLE
JContainersVR.dll reported as missing when it is present

### ISSUE THREAD

**Issue by davidowens** [Synthesis-Collective/SynthEBD#51]
I'm getting the following error in the log saying that jContainersVR.dll is missing

> Could not find JContainersVR.dll from JContainers at D:\Gaming\Steam\steamapps\common\SkyrimVR\Data\SKSE\Plugins\JContainersVR.dll
> Please make sure JContainers is enabled.

I've doubled checked because I thought it might be a Mod organizer Virtual File System problem, and it's definitely there.

I think maybe there is a misplaced brace or exclaimation mark in this new check

[/SynthEBD/General_Aux/MiscValidation.cs#L139](https://github.com/Synthesis-Collective/SynthEBD/blame/50e37c264ecedf8b23a5ae427ddb694b2f695a2f/SynthEBD/General_Aux/MiscValidation.cs#L139)

**Comment by davidowens** [comment]
maybe is should be

`if (
  {checkSE && !File.Exists(dllPathSE_AE)) || 
  (checkVR && !File.Exists(dllPathVR))
)`

**Comment by Piranha91** [comment]
Thanks! I'll incorporate this into the next release.

**Comment by Piranha91** [comment]
Added in to v0.8.2 - please let me know if you still see the error in the current version. Thank you again!
