### ISSUE TITLE
Record Templates not being found 

### ISSUE THREAD

**Issue by geesesuck** [Synthesis-Collective/SynthEBD#53]
Whenever I run the patcher, I get this error repeating for all the templates from Record Templates.esp: 
```
Could not find record template plugin 000800:Record Templates.esp
Error: Cannot resolve template NPC with FormKey 000800:Record Templates.esp
```
Any clue how to fix this?

**Comment by Piranha91** [comment]
This seems like a config file issue rather than a problem with SynthEBD. Which config file is it? If it’s not one of the official ones, can you upload a copy?

**Comment by geesesuck** [comment]
Demoniac and TSM

**Comment by Piranha91** [comment]
Do you have record templates.esp in your SynthEBD record templates folder? And are you using a portable Settings folder?

**Comment by geesesuck** [comment]
Yes I do have the esp, also I don't know how to use a portable settings folder. If it helps, I am using vortex.

**Comment by Piranha91** [comment]
Weird. I’ll try to set up vortex tonight and see if I get something similar. In the meantime, what do you get if you go to the status log and click the environment button at the bottom?

**Comment by geesesuck** [comment]
`Load Order: 
(+) Skyrim.esm
(+) Update.esm
(+) Dawnguard.esm
(+) HearthFires.esm
(+) Dragonborn.esm
(+) ccASVSSE001-ALMSIVI.esm
(+) ccBGSSSE001-Fish.esm
(+) ccTWBSSE001-PuzzleDungeon.esm
(+) ccEEJSSE001-Hstead.esm
(+) ccBGSSSE016-Umbra.esm
(+) ccBGSSSE031-AdvCyrus.esm
(+) ccBGSSSE067-DaedInv.esm
(+) ccBGSSSE025-AdvDSGS.esm
(+) ccEEJSSE005-Cave.esm
(+) ccAFDSSE001-DweSanctuary.esm
(+) ccBGSSSE002-ExoticArrows.esl
(+) ccBGSSSE003-Zombies.esl
(+) ccBGSSSE004-RuinsEdge.esl
(+) ccBGSSSE005-Goldbrand.esl
(+) ccBGSSSE006-StendarsHammer.esl
(+) ccBGSSSE007-Chrysamere.esl
(+) ccBGSSSE010-PetDwarvenArmoredMudcrab.esl
(+) ccBGSSSE011-HrsArmrElvn.esl
(+) ccBGSSSE012-HrsArmrStl.esl
(+) ccBGSSSE014-SpellPack01.esl
(+) ccBGSSSE019-StaffofSheogorath.esl
(+) ccBGSSSE020-GrayCowl.esl
(+) ccBGSSSE021-LordsMail.esl
(+) ccMTYSSE001-KnightsoftheNine.esl
(+) ccQDRSSE001-SurvivalMode.esl
(+) ccQDRSSE002-Firewood.esl
(+) ccBGSSSE018-Shadowrend.esl
(+) ccBGSSSE035-PetNHound.esl
(+) ccFSVSSE001-Backpacks.esl
(+) ccEEJSSE002-Tower.esl
(+) ccEDHSSE001-NorJewel.esl
(+) ccVSVSSE002-Pets.esl
(+) ccBGSSSE037-Curios.esl
(+) ccBGSSSE034-MntUni.esl
(+) ccBGSSSE045-Hasedoki.esl
(+) ccBGSSSE008-Wraithguard.esl
(+) ccBGSSSE036-PetBWolf.esl
(+) ccFFBSSE001-ImperialDragon.esl
(+) ccMTYSSE002-VE.esl
(+) ccBGSSSE043-CrossElv.esl
(+) ccVSVSSE001-Winter.esl
(+) ccEEJSSE003-Hollow.esl
(+) ccBGSSSE038-BowofShadows.esl
(+) ccBGSSSE040-AdvObGobs.esl
(+) ccBGSSSE050-BA_Daedric.esl
(+) ccBGSSSE052-BA_Iron.esl
(+) ccBGSSSE054-BA_Orcish.esl
(+) ccBGSSSE058-BA_Steel.esl
(+) ccBGSSSE059-BA_Dragonplate.esl
(+) ccBGSSSE061-BA_Dwarven.esl
(+) ccPEWSSE002-ArmsOfChaos.esl
(+) ccBGSSSE041-NetchLeather.esl
(+) ccEDHSSE002-SplKntSet.esl
(+) ccBGSSSE064-BA_Elven.esl
(+) ccBGSSSE063-BA_Ebony.esl
(+) ccBGSSSE062-BA_DwarvenMail.esl
(+) ccBGSSSE060-BA_Dragonscale.esl
(+) ccBGSSSE056-BA_Silver.esl
(+) ccBGSSSE055-BA_OrcishScaled.esl
(+) ccBGSSSE053-BA_Leather.esl
(+) ccBGSSSE051-BA_DaedricMail.esl
(+) ccBGSSSE057-BA_Stalhrim.esl
(+) ccBGSSSE066-Staves.esl
(+) ccBGSSSE068-Bloodfall.esl
(+) ccBGSSSE069-Contest.esl
(+) ccVSVSSE003-NecroArts.esl
(+) ccVSVSSE004-BeAFarmer.esl
(+) ccFFBSSE002-CrossbowPack.esl
(+) ccBGSSSE013-Dawnfang.esl
(+) ccRMSSSE001-NecroHouse.esl
(+) ccEDHSSE003-Redguard.esl
(+) ccEEJSSE004-Hall.esl
(+) ccKRTSSE001_Altar.esl
(+) ccCBHSSE001-Gaunt.esl
(+) Unofficial Skyrim Special Edition Patch.esp
(+) Unofficial Skyrim Creation Club Content Patch.esl
(+) Vanilla Scripts Enhanced.esl
(+) Expressive Facegen Morphs.esl
(+) High Poly Head.esm
(+) WhiterunHoldForest.esp
(+) Occ_Skyrim_Tamriel.esp
(+) 3DNPC.esp
(+) Better Dynamic Snow SE - DisableRefs.esm
(+) MorrowindCreatures.esl
(+) EVGAnimatedTraversal.esl
(+) Schlongs of Skyrim - Core.esm
(+) Resources - The Great Cities.esp
(+) DynDOLOD.esm
(+) SkyUI_SE.esp
(+) Obsidian Weathers.esp
(+) SMIM-SE-Merged-All.esp
(+) Better Dynamic Snow SE.esp
(+) ICNs_ImmersiveCollegeNPCs.esp
(+) FNIS.esp
(+) (SGC) SkySA.esp
(+) Weapons Armor Clothing & Clutter Fixes.esp
(+) ESOimports.esp
(+) Relationship Dialogue Overhaul.esp
(+) The Great Cities - Minor Cities and Towns.esp
(+) TGFoW - CC Patch.esp
(+) Cutting Room Floor.esp
(+) OCW_Obscure's_CollegeofWinterhold.esp
(+) SkyrimUnleveled.esp
(+) SoundsofSkyrimComplete.esp
(+) The Great Town of Ivarstead.esp
(+) The Great Town of Karthwasten.esp
(+) The Great Town of Shor's Stone.esp
(+) The Great Village of Kynesgrove.esp
(+) The Great Village of Old Hroldan.esp
(+) OBIS SE.esp
(+) OCW_ICNs_OE_FEPatch.esp
(+) Immersive Encounters.esp
(+) The Great Village of Mixwater Mill.esp
(+) SeranaDialogAddon.esp
(-) Particle Patch for ENB SSE.esp
(+) Hothtrooper44_ArmorCompilation.esp
(+) Realm of Lorkhan - Custom Alternate Start - Choose your own adventure.esp
(+) ogCannibalDraugr.esp
(+) WhiterunAddition.esp
(+) CFTO.esp
(+) Lit Road Signs.esp
(+) SkyrimSewers.esp
(+) WayshrinesIFT.esp
(+) s6o6t Lore - Oblivion Gates.esp
(+) OCW_TGCs_FEPatch.esp
(+) WayshrinesIFT - Great Forest of Whiterun Hold patch.esp
(+) OCW_CRF_FEPatch.esp
(+) DealingwithBackstories.esp
(+) Book Covers Skyrim - Lost Library.esp
(+) BloodHorkers.esp
(+) Immersive Patrols II.esp
(+) GrahlsOnSolstheim.esp
(+) GFoWH - Whiterun Expansion Redone compatibility patch.esp
(+) OCW_BCS-LL_FEPatch.esp
(+) s6o6t Lore - Dark Anchors Ruins and Dolmens.esp
(+) ForgottenCity.esp
(+) Skyland-AIO.esp
(+) 1Scamp.esp
(+) 1Daedroths.esp
(+) CoMAP - Authors Cut.esp
(+) CFTO-Lanterns.esp
(+) CFTO-CoveredCarriages.esp
(+) Clannfear.esp
(+) Shadow of Skyrim.esp
(+) Apocalypse - Magic of Skyrim.esp
(+) Around the Fire.esp
(+) Bandit Lines Expansion.esp
(+) BetterThirdPersonSelection.esp
(+) Building_Bridges_Skyrim.esp
(+) CFTO_fix.esp
(+) CFTO bittercup fix.esp
(+) CiceroFemaleSE.esp
(+) CiceroFemaleConversion.esp
(+) CoMAP - Jorrvaskr Marker.esp
(+) LustmordVampireArmor.esp
(+) CoMAP - KhajiitCaravans.esp
(+) Crimson Blood Armor.esp
(+) Melodies of Civilization.esp
(+) Dawnguard Music Overhaul.esp
(+) TheCleaner.esp
(+) DiverseDragonsCollectionSE.esp
(+) ForswornVarietyArmorPack.esp
(+) Fashions of the Banditry.esp
(+) First Person Camera Height Fix.esp
(+) FEC.esp
(+) Galactic eyes.esp
(+) UUNP Vanilla Outfits.esp
(+) HIMBO.esp
(+) RaceMenuMorphsHIMBO.esp
(+) High Poly Head Vampire Fix.esp
(+) Hun Lovaas.esp
(+) Beards.esp
(+) Brows.esp
(+) IAWeightFixes.esp
(+) Hothtrooper44_Armor_Ecksstra.esp
(+) Immersive Speechcraft.esp
(+) 3DNPC0.esp
(+) 3DNPC1.esp
(+) 3DNPC - CRF Patch.esp
(+) KS Hairdo's.esp
(+) KarstaagReborn.esp
(+) MCMHelper.esp
(+) McmRecorder.esp
(+) NPCs_Wear_Amulets_Of_Mara.esp
(+) NB-Scars.esp
(+) OCW_WACCF_FEPatch.esp
(+) OCW_SoS_FEPatch.esp
(+) OCW_3DNPC_FEPatch.esp
(+) OCW_MusicPatch_VanillaPlus.esp
(+) chfshPlayerVoicesets.esp
(+) Precision.esp
(+) DisableVanillaLoadingScreensUSSEP.esp
(+) RaceMenu.esp
(+) RaceMenuPlugin.esp
(+) HagravenSkinShaders.esp
(+) Realm of Lorkhan - My Edits.esp
(+) NPCs_Wear_Amulets_Of_Mara - SDA Patch.esp
(+) SDA DX Crimson Blood Patch.esp
(+) SDA RDO Patch.esp
(+) SOS - Smurf Average Addon.esp
(+) SOS - VectorPlexus Muscular Addon.esp
(+) SOS - VectorPlexus Regular Addon.esp
(+) Schlongs of Skyrim.esp
(+) Seasons of Skyrim - The Great Village of Kynesgrove fix.esp
(+) Seasons of Skyrim - The Great Village of Mixwater Mill fix.esp
(+) SnowOverSkyrim.esp
(+) SFO_SkinFeatureOverlays.esp
(+) SkyHUD.esp
(+) Skyland Watercolor - Slow Green-Vanilla.esp
(+) SoS_Obsidian_Patch.esp
(+) Starlit Lakes Loading Screens.esp
(+) Still.esp
(+) Record Templates.esp
(+) The Eyes Of Beauty - Elves Edition.esp
(+) TheEyesOfBeauty.esp
(+) UIExtensions.esp
(+) autoBodyAE.esp
(+) BHUNP3BBB.esp
(+) RaceMenuMorphsBHUNP.esp
(+) VisualAnimatedEnchants.esp
(+) SOSRaceMenu.esp
(+) XPMSE.esp
(+) [Dint999] FacePartMod.esp
(+) [Dint999] FacePartMod+Galactic eyes.esp
(+) [dint999] HairPack02.esp
(+) MLU.esp
(+) Helgen Reborn.esp
(+) MLU - CRF.esp
(+) MLU - Immersive Armors.esp
(+) MLU - WaCCF.esp
(+) OCW_MLU_FEPatch.esp
(+) Ordinator - Perks of Skyrim.esp
(+) Apocalypse - Ordinator Compatibility Patch.esp
(+) Ordinator_WACCF_Patch.esp`

**Comment by Piranha91** [comment]
Still working on getting SynthEBD up and running with Vortex. In the meantime, do you get the green dot in your TSM record templates menu?

![image](https://user-images.githubusercontent.com/63175798/188561188-5da2bd13-72cf-4852-8a00-49319f86745b.png)

**Comment by Piranha91** [comment]
Ok, I can now confirm that I was able to run SynthEBD through vortex by adding it to the dashboard, installing the TSM config file, and running SynthEBD through the dashboard. It created a valid .esp file distributing the TSM skins. The only caveat was that I had to manually specify the output folder, or the generated .esp would get lost - I'll fix this in the next version but this isn't the problem you're having. Sounds like there might be something going on with your setup. As mentioned in the previous post, do you see the green dot in TSM's record templates menu? Additionally, if you go to your dashboard and hit the 3 dot menu for SynthEBD -> Edit, where does it point to? Just wondering if you might have multiple instances of SynthEBD running, and maybe the default record templates are missing in one of them. Finally, just want to confirm that your portable settings folder is empty. Mine is not, but yours should be unless you've read the readme for how to use it. 
![image](https://user-images.githubusercontent.com/63175798/188568006-5c222296-c397-41da-86a3-c2846b12ba9a.png)

**Comment by geesesuck** [comment]
The dots for me are red, The folder is empty, and the target for the dashboard executable is the .exe in the unzipped folder in my mod staging folder, `D:\Modding\SynthEBD_v0.8.1.5\SynthEBD.exe`

**Comment by Piranha91** [comment]
I wonder if it maybe doesn’t like that the exe lives in the staging folder. What happens if you move the whole SynthEBD installation to a non-vortex-managed directory?

**Comment by geesesuck** [comment]
Putting it into the data directory of Skyrim solved the issue of not finding the record templates, yet status log now says there are no valid asset packs for all the npcs while running

**Comment by Piranha91** [comment]
I think putting it in the data directory is also maybe not ideal. I can't tell you off the top of my head what, if anything, it might interfere with, but the accepted best practice is to put it in a separate folder entirely. For example, mine lives in D:\MO2\
tools\SynthEBD, alongside tools\DynDOLOD, tools\SSEedit, etc. To troubleshoot the status log, can you verify that your config files are active?

![image](https://user-images.githubusercontent.com/63175798/188701456-3d1d7658-dd7c-45d4-a2e0-54886e6dc53b.png)

Does an output .esp get generated? If so, does it contain any NPC entries? Does the patcher actually give you the "no valid asset packs" warning for every NPC, or just a (large) subset of them? If you click the "Validate Configs" button, do you get any errors?

**Comment by geesesuck** [comment]
SynthEBD.esp, the only esp in output, does alter the heights of every NPC and alter the face part for some, but that is it. This occurred after setting it back up in a new location, and the config files are activated with no errors

**Comment by geesesuck** [comment]
[error.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9500475/error.txt)
is the log I get.

**Comment by Piranha91** [comment]
In the general settings menu, can you add one of the failed NPCs (say, Ralof, for example) to the Verbose Mode for Specific NPCs list, and then paste the resulting log from SynthEBD\Logs?

**Comment by geesesuck** [comment]
[Log.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9503090/Log.txt)
Had to copy paste it from the .xml file, looks like Nord is missing from config file, will look a bit more into it

**Comment by Piranha91** [comment]
I see something that's not adding up with the config file. Is it one of the Demoniac jsons from the SynthEBD git page? If so, can you tell me which installer options you chose? What's confusing are the following lines in your log:

```Subgroup HDE.BDM(BlankDetailMap)  is invalid because the NPC matches one of its disallowed attributes: 
							{Face Texture: [SkinHeadFemaleBretonComplexion_Age40, SkinHeadFemaleDarkElfComplexion_Age40, SkinHeadFemaleHighElfComplexion_Age40, SkinHeadFemaleImperialComplexion_Age40, SkinHeadFemaleOrcComplexion_Age40, SkinHeadFemaleRedguardComplexion_Age40, SkinHeadFemaleWoodElfComplexion_Age40, SkinHeadFemaleNordComplexion_Age40, SkinHeadFemaleBretonComplexion_Age50, SkinHeadFemaleDarkElfComplexion_Age50, SkinHeadFemaleHighElfComplexion_Age50, SkinHeadFemaleImperialComplexion_Age50, SkinHeadFemaleOrcComplexion_Age50, SkinHeadFemaleRedguardComplexion_Age50, SkinHeadFemaleWoodElfComplexion_Age50, SkinHeadFemaleNordComplexion_Age50]}
							
							Subgroup HDE.R(Rough)  is invalid because the NPC does not match any of its allowed attributes: Face Texture: [SkinHeadFemaleBretonComplexion_Rough01, SkinHeadFemaleDarkElfComplexion_Rough01, SkinHeadFemaleHighElfComplexion_Rough01, SkinHeadFemaleImperialComplexion_Rough, SkinHeadFemaleOrcComplexion_Rough01, SkinHeadFemaleRedguardComplexion_Rough01, SkinHeadFemaleWoodElfComplexion_Rough01, SkinHeadFemaleNordRough, SkinHeadFemaleOldComplexion_Rough]
							
							Subgroup HDE.F(Freckles)  is invalid because the NPC does not match any of its allowed attributes: Face Texture: [SkinHeadFemaleBretonComplexion_Frekles, SkinHeadFemaleDarkElfComplexion_Frekles, SkinHeadFemaleHighElfComplexion_Frekles, SkinHeadFemaleImperialComplexion_Frekles, SkinHeadFemaleNordComplexion_Frekles, SkinHeadFemaleOrcComplexion_Frekles, SkinHeadFemaleRedguardComplexion_Frekles, SkinHeadFemaleWoodElfComplexion_Frekles, SkinHeadFemaleOldComplexion_Frekles]
							
							Asset Pack Demoniac 8K UNP is invalid for NPC Legate Rikke | Rikke | 0132A1:Skyrim.esm because no subgroups within HDE (Head Detail) are compatible with this NPC.
```
It looks like it never evaluates Age 40 (which is what Rikke is probably supposed to receive) and Age 50, as if they weren't there. Is this what your Subgroups tree looks like under Head Detail?

![image](https://user-images.githubusercontent.com/63175798/188828941-6141a282-f4be-45e0-b745-021f20ecebaa.png)

**Comment by Piranha91** [comment]
Oh I see what the issue is. You'll need to re-enable distribution of the Age40 and Age50 subgroups. 

![image](https://user-images.githubusercontent.com/63175798/188829638-ce4892ca-667b-46cf-888b-fd2919e151e1.png)

I'm not sure why I disabled them - either I thought those textures had too much of a neck seam, or I just thought they looked inferior and assumed that someone who installed Demoniac would also install Tempered or Mature to cover the Age40/Age50 NPCs. But if you're using standalone, you'll need to re-enable those subgroups because there's no other config to cover those NPCs.

If this is the only issue though, it should only be Age40/Age50 female NPCs not getting patched, but you said none of the NPCs were getting textures. Is that still the case?

**Comment by geesesuck** [comment]
Yup, this seemed to have cleared it up. Only ones missing are Khajiit files which I got the configs for. Thanks boss!
