### ISSUE TITLE
Body descriptors not working?

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#54]
Hi, I'm running into some weird behavior while trying to understand how Bodyslide Body Descriptors work...

Firstly, it seems that removing all created descriptors does not delete them from the OBodySettings.json file. After removing them using SynthEBD, they are gone from the GUI, but are still inside the DescriptorRules section of the file... My file is kind of a mess now lol...

Secondly, I can't get the descriptor rules to work... I've tried creating a new Body Descriptor and annotated it to two test Bodyslides (descriptor and bodyslides with default rules). Then, on "whole config distribution rules" of a texture asset pack, I selected the new body descriptor on "allowed bodyslide descriptors". After running the patch and checking the distribution logs for the asset pack, the assigned Bodyslide Preset is different from those two test bodyslides assigned earlier... the patcher randomly chooses from the other bodyslides evaluating only the rules from each BodySlide Preset file that I have. It seems that Body Descriptors (and its rules) are ignored by the patcher...

Maybe I'm doing something wrong here? Shouldn't the expected behaviour be the assignment of the asset pack AND one of the two bodyslide presets related to the Body Descriptor?

**Comment by Piranha91** [comment]
Ah, I see the issue. The bodyslide assigner checks descriptors assigned to subgroups, but the whole-config distribution rules were a later addition and I forgot to have them check those as well. I'll fix that in the next update. Will look into the descriptors not getting deleted as well. Thanks for the report!

**Comment by leonardovcr** [comment]
Nice!

On another note, do BodySlide presets inherit Body Descriptor rules? As in, if I have multiple body presets that I intend to use for Nord race for example, would the patcher understand that behavior if I annotate those presets with a Descriptor containing an Allowed Race Grouping for Nord Race?

I'm asking that because I ran some tests and couldn't get any body descriptor rule to actually be recognized by the patcher. Only the rules set directly on the bodyslide presets seem to have any effect.

**Comment by Piranha91** [comment]
I'll have to dig into the code and see. They definitely should inherit descriptor rules, but descriptor rules were another late addition (I think about the same time as whole-config rules) so I might also have not fully handled them. I have a few other tasks I need to take care of first, but adding this to the queue.

**Comment by Piranha91** [comment]
I've done some work on my end to address issues #2 and #3, and now I'm looking at issue #1 (descriptors not getting deleted) and I can't seem to replicate it. I might have addressed it inadvertently through the other changes, but I just want to make sure. What exactly happens when you remove a descriptor? You say it gets removed from UI but not from json - does it get re-loaded into the UI next time you launch SynthEBD? Does it get duplicated, or just stays as original? Does the order of the descriptors change? Is it all descriptors, or only the default ones?

**Comment by leonardovcr** [comment]
I did a more careful testing and it seems that the "TemplateDescriptors" of the .json are indeed being added/deleted when I add/remove them (Body Descriptors-Category-Value and quit app) using the UI.

However, what seems to be problematic are the "DescriptorRules/Signatures" of the .json file... I have lots of "DescriptorSignature" entries which I have deleted a long time ago.

If I create a brand new Body Descriptor-Category-Value, add some rules, and quit the App, I can see that a relevant "DescriptorSignature" entry is created, but rules are not persisted to json file (no Signatures are created). Checking with the GUI again, the rules aren't there anymore. It seems that rules (signatures) are only persisted if I launch the App again, add the rules one more time, and quit the app.

Also, if I delete the whole Body Descriptor through the GUI, the TemplateDescriptor is correctly deleted, but the related Signatures are not :/

**Comment by Piranha91** [comment]
Ah I see. Ok, so the good news is that I have one last thing to figure out and then I’ll be same to release a version that doesn’t have this issue. The bad news is that I’ve extensively refactored how the descriptor rules are stored in a way that is not really recoverable, so you’ll need to recreate any rules you already have made (they’ll be blanked in the UI). Sorry for the inconvenience!

**Comment by Piranha91** [comment]
These issues should be fixed in 0.8.2 (Again, any per-Descriptor distribution rules will need to be re-made). Please let me know if any of the issues persist - I've verified patcher execution but I'm a bit low on the workload:bandwidth ratio and would appreciate help testing!

**Comment by leonardovcr** [comment]
Nice, it seems that those issues with the descriptors and its rules not being properly persisted to file are gone now :)

However, it looks like an asset's "Whole Config Distribution Rules" are still ignoring its "Allowed Bodyslide Descriptor" :( 
The patcher is still assigning a random bodyslide which is not the one I defined and configured in the Whole Config's Allowed Bodyslide Descriptor...

I also did a test setting the bodyslide descriptor to an asset's subgroup this time (the head diffuse subgroup) but got this error when running the patcher: "Allowed descriptor Race: Nord is invalid because it is not contained within your O/AutoBody descriptors"

I'm still doing some tests to check if bodyslides are inheriting their body descriptor rules, and so far so good. I think that is solved now too :)

**Comment by leonardovcr** [comment]
Just got another strange inconsistency while running the patcher for a DarkElfVampireRace NPC:

Preset PA44_Elves_CBBE is invalid because the rules for its descriptor Race: HighElf have Allowed Races that do not include the current NPC's race
Preset PA44_Elves_CBBE is invalid because the rules for its descriptor Race: WoodElf have Allowed Races that do not include the current NPC's race
Preset PA44_Orc_CBBE is invalid because the rules for its descriptor Race: Orc have Allowed Races that do not include the current NPC's race

Chose BodySlide Preset: PA44_Orc_CBBE

Sooo... I've created a Descriptor (Category) with one "value" for each race, and annotated the PA44_Elves_CBBE Bodyslide to each one of the elven races value and the PA44_Orc_CBBE to the Orc race value. Allowed Race Groupings for each value has its corresponding Race and RaceVampire as one Race Grouping:

![image](https://user-images.githubusercontent.com/13605450/189512765-f5a38923-ae98-40b7-8fb0-7d1aaebbe80d.png)

Shouldn't the patcher have chosen the PA44_Elves_CBBE instead of the PA44_Orc_CBBE, since the former is annotated to a descriptor which has an entry for DarkElfVampires? 

Here's the BodySlide settings:

![image](https://user-images.githubusercontent.com/13605450/189512861-bf259f61-3477-413d-8180-54406cd9ce22.png)
![image](https://user-images.githubusercontent.com/13605450/189512918-9b3aca5c-ff2d-4bb7-94d1-ed94620cebba.png)

**Comment by Piranha91** [comment]
Ah, I just made a bugfix release before seeing your last post. The first issue is addressed in 0.8.2.1 - type on my part. Looking at the more recent one now; that obviously won't be fixed in the current version :)

**Comment by Piranha91** [comment]
Think I found the issue :). Sorry, tired eyes!

![image](https://user-images.githubusercontent.com/63175798/189513142-ca8176dc-4c8c-4853-b7af-729ea8719b38.png)

**Comment by Piranha91** [comment]
Added the missing lines to 0.8.2.2. Keep the bug reports coming if you've got them ;). Will try to address them as available. In the meantime, adding you to the acknowledgements in the readme for your extensive bug hunting success - thanks!

**Comment by leonardovcr** [comment]
No problem, glad to help :)

Latest version (0.8.2.2) did indeed fix Whole Config Distribution/Allowed Bodyslide Descriptors problem 👍 

Now from what I could test, there are still some issues to be fixed: 

One is the assignment of Allowed/Disallowed Bodyslide Descriptors to an asset's pack _subgroup_, which gives the following error when validating the config file:

```
Subgroup HD.V:Vampire within branch 1
Allowed descriptor Test: Test is invalid because it is not contained within your O/AutoBody descriptors
```

And the other issue is the bodyslide distribution from my last post (the DarkElfVampireRace NPC)... maybe I'm misuderstanding the patcher rules, but when checking the PA44_Elves_CBBE preset, it is not clear if the patcher is accepting the Bodyslide Preset and not distributing it due to random chance (which is fine I think), or if the patcher discards the preset altogether since it is annotated with descriptor values that has allowed AND unallowed races (Category:Values -> Race:HighElf,WoodElf,DarkElf). 
Maybe the patcher is only checking the first Value (HighElf) and since it does not match, it does not even bother to check the other values (WoodElf,DarkElf)?

```
Preset PA44_Elves_CBBE Current NPC matches the following forced attributes: 
{NPC: [03315A:Skyrim.esm]} (Weighting: 1)					
Preset PA44_Elves_CBBE is invalid because the rules for its descriptor Race: HighElf have Allowed Races that do not include the current NPC's race
Preset PA44_Human_CBBE is invalid because the rules for its descriptor Race: Nord have Allowed Races that do not include the current NPC's race
Preset PA44_Orc_CBBE is invalid because the rules for its descriptor Race: Orc have Allowed Races that do not include the current NPC's race
Chose BodySlide Preset: CustomPreset
```

Finally, there's also a strange warning when launching the app that I didn't notice before:

`Warning: The forced Asset Pack New Asset Pack for NPC Lydia (0A2C8E:Skyrim.esm) no longer exists.`

I made this NPC assignment with only a Forced Bodyslide selected, and did not choose a forced asset pack (it has a null value it seems), which is my intended behavior (want it to be random). Maybe the warning is superfluous?

**Comment by Piranha91** [comment]
Ah, ok:

1) Test is invalid because it is not contained within your O/AutoBody descriptors. 
- I can only replicate this under specific circumstances, but I think I have it fixed in 0.8.2.3.

2) Preset PA44_Elves_CBBE is invalid because the rules for its descriptor Race: HighElf
- I think there's a misunderstanding here about what Descriptors are for and how their rules work. Descriptors are meant to annotate what the bodyslide looks like, so that it can be paired with the correct textures (e.g. avoiding textures with defined muscularity getting paired with a chubby bodyslide). If descriptors have rules attached to them, they will all be evaluated individually - e.g. if you have a bodyslide tagged with "dark elf" and "high elf", then the patcher will first evaluate the dark elf rules, see that your dark elf NPC is valid, but then evaluate the high elf rules and see that the current NPC is invalid, so the parent bodyslide must therefore also be invalid. For the moment, That being said, I can see how creating custom groups with their own rule sets could be appealing, and could work similarly to descriptors but following OR logic instead of AND. I could look into adding that in a future update.

3) Thanks for the catch - fixed this in v0.8.2.3. You will probably still see the error on first launch, but it should then clear itself when the new format gets saved upon closing and you shouldn't see it again afterward.

**Comment by leonardovcr** [comment]
No I'm not :) just a curious player.
But I'm trying to set up his bodyslides in my game. Great modder btw!

**Comment by leonardovcr** [comment]
I think we can close this issue now, v0.8.2.3 solved issues 1 and 3 👍 Issue 2 is not really an issue but just the way the patcher works as you kindly explained. Thanks!
