### ISSUE TITLE
Subgroup HDE.BDM:BlankDetailMap within branch 5 // Using Stock Game

### ISSUE THREAD

**Issue by qcklyrainbow** [Synthesis-Collective/SynthEBD#56]
Errors detected in Config File Demoniac 4K CBBE
Subgroup HDE.BDM:BlankDetailMap within branch 5
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\male\blankdetailmap.dds or any BSA archives corresponding to Skyrim.esm
Subgroup HDE.R:Rough within branch 5
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\female\femaleheaddetail_rough.dds or any BSA archives corresponding to Skyrim.esm
Subgroup HDE.F:Freckles within branch 5
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\female\femaleheaddetail_frekles.dds or any BSA archives corresponding to Skyrim.esm
Subgroup BN.E:Elder within branch 7
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\femaleold\femalebody_1_msn.dds or any BSA archives corresponding to Skyrim.esm
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\femaleold\femalebody_1_msn.dds or any BSA archives corresponding to Skyrim.esm
Subgroup HAN.E:Elder within branch 11
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\Actors\Character\FemaleOld\FemaleHands_1_msn.dds or any BSA archives corresponding to Skyrim.esm

Errors detected in Config File Vitruvia SOS 4K
Subgroup HDE.R02:Rough02 within branch 5
No file exists at F:\Licentia\Stock Game\data\Skyrim.esm\Textures\actors\character\male\maleheaddetail_rough02.dds or any BSA archives corresponding to Skyrim.esm

Could not run the patcher. Please correct the errors above.

General settings in SynthEBD:
![image](https://user-images.githubusercontent.com/113746975/190839045-27ec4126-65a5-440a-a606-2bec8f518ee5.png)

SynthEBD is installed in Licentia\tools and run through MO2.  Executable settings:
![image](https://user-images.githubusercontent.com/113746975/190839273-d7d2f2e1-a918-43d2-8ec2-ee677e3f104b.png)

Using the most recent build.

**Comment by Piranha91** [comment]
It looks like it's having trouble reading the game data from your custom game installation. If I go to the Head Detail subgroup in Demoniac, I see a green box for the source:

![image](https://user-images.githubusercontent.com/63175798/190840282-c5a2559c-225a-4f9d-badb-3bc11ff10645.png)

I'm assuming for you it's red? Do you have Skyrim.esm in F:\Licentia\Stock Game\data? If yes, could you go to the status log, click "Environment Details", then "Copy to Clipboard", and paste it here?

**Comment by qcklyrainbow** [comment]
Yes, correct; it's red.  All of the Head Detail options are (BlankDetailMap, Rough, Freckles, Age40, Age50).

Stock Game\Data folder:
![image](https://user-images.githubusercontent.com/113746975/190840335-975606d4-4fe5-4bc0-af31-6bf33108b10c.png)

So no Textures1-8.bsa.  Interesting.  Adding them in now, and we'll see!

**Comment by qcklyrainbow** [comment]
The patching process is running, so I think this can be closed.

**Comment by Piranha91** [comment]
Cool, I'll go ahead and close the issue - feel free to open a new one if something else comes up.
