### ISSUE TITLE
NOT ISSUES. One suggestion. About language.

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#58]
I have enjoyed your work.
However, when I run the patch in Japanese, the characters are garbled.
Is there any way to fix this as skyrim has many Japanese, Chinese, and Korean players?

**Comment by Piranha91** [comment]
Is it the same problem as this issue? https://github.com/Synthesis-Collective/SynthEBD/issues/49 

It's very strange because SynthEBD shouldn't touch things like names explicitly. For you does it also change characters (letters) that shouldn't need to be changed?

**Comment by Noggog** [comment]
You might need to expose language settings similar to Synthesis  (and/or integrate into synthesis and you'll get them that way)

**Comment by Daikichi-Takahey** [comment]
I just upgraded and the garbled text is gone!

Thank you Piranha91 and Noggog.

**Comment by Daikichi-Takahey** [comment]
However, the Under-there patcher also has a problem with garbled characters. If you don't mind, does the Under-there patcher have any opinions?

![スクリーンショット (53)](https://user-images.githubusercontent.com/100354903/190964068-6a70a1f4-378e-497d-9369-539bb1f11377.png)

**Comment by Piranha91** [comment]
Are you running Under There with Matched mutagen versioning? I may need to update the patcher to use the latest Mutagen version, which seems to fix translations. I'll put that on the priority list after releasing SynthEBD 0.8.3 in a few days.

**Comment by Daikichi-Takahey** [comment]
Yes. Go to the Under-there page on this subject.
Thanks both of you for your quick replies.
