### ISSUE TITLE
I have a problem with tabs going up and down in a specific NPC assignment

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#6]
I think it's a low priority because it works 100% of the time as long as I don't move the tabs.

https://user-images.githubusercontent.com/100354903/157338695-d7cbd1a4-b2e3-4793-a6c4-d066d203da10.mp4

**Comment by Piranha91** [comment]
Fixed (thanks 100% to Noggog) in v0.4.0.
