### ISSUE TITLE
Pressing the + button on the subgroup four times freezes it.

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#60]
When creating a new config file, pressing the + button for a subgroup freezes.
No matter how many times I create a new config file, it freezes for the fourth time.

https://user-images.githubusercontent.com/100354903/191948124-3553fa53-9e04-4416-af90-4e483bfa700d.mp4

**Comment by Piranha91** [comment]
Thanks for the report - I actually caught this on my end a couple days ago and it will no longer freeze in tomorrow's release. However, please keep the issue open - in the following release I'd like to make further improvements to how this is handled.

**Comment by Piranha91** [comment]
Sorry for the delay - should be fixed in 0.8.3. Please keep this issue open still - the fix can still be improved and otherwise I'll forget.
