### ISSUE TITLE
Troubles with OStim

### ISSUE THREAD

**Issue by evgaldh** [Synthesis-Collective/SynthEBD#61]
Hello Piranha91, i don't know where else to ask that question, but i got a problem with [OStim](https://www.nexusmods.com/skyrimspecialedition/mods/40725). When i start animation, Female NPCs and only they got their head textures back to vanilla or any other texture overwrites vanilla textures. Swaped textures stays unless i manually reenabling that NPC through the console.
I don't exactly know whethe this related to OStim or SyntEBD, but when i don't have SyntEBD.esp activated that 'swap' also doesn't happening. 
Worth mentioned that not all NPCs are getting swaped. I noticed nord NPCs, elves NPCs but that requires some more research). Male NPCs doesn't swaping.

**Comment by Piranha91** [comment]
Yep it’s a known issue with compatibility between OStim/SL and the underlying EBD Papyrus scripts. Trying to find a fix is on my to do list but I’m a bit crushed for time this month and I need to prioritize SynthEBD-specific issues first.

**Comment by Piranha91** [comment]
I did a brief test a while ago with OStim NG and it looks like this issue does not occur. I'm not planning to implement backwards compatibility with the original OStim, though others are free to do so if they can figure out the cause of the clash.
