### ISSUE TITLE
File not found ...\Skyrim Special Edition\Skyrim.ini for SkyimVR.

### ISSUE THREAD

**Issue by icarus342** [Synthesis-Collective/SynthEBD#62]
After installing **SynthEBD.-.Demoniac.Texture.7z** via "Install Config From Archive", the application displays a pop up error indicating that SynthEBD has crashed with a file not found error for '...\Skyrim Special Edition\Skyrim.ini'. After closing and opening SynthEBD.exe, I receive a Markup.XamlReader.RewrapException in addition to the same file not . After deleting the Demoniac json config file from Asset Packs folder, both errors cease.

Other notes:
- Error occurs from installing either:
	- **SynthEBD.-.Demoniac.Texture.7z**
	- **SynthEBD.-.Vitruvia.7z**
- No issues installing:
	- SynthEBD.-.Mature.Skin.7z
	- SynthEBD.-.Bijin.Skin.7z
	- SynthEBD.-.Tempered.Skins.for.Males.7z
	- SynthEBD.-.FA.Dibellan.7z
- From the Vortex mod manager, it appears "SynthEBD - Demoniac Skin CBBE" was created successfully.
- .NET Runtime 6.0.9 (x64) installed
- SkyrimVR installed.
- SkyrimSE not installed. _(I don't think I've ever had SkyrimSE installed on this installation of Windows 10.)_
- Invalid path on my system:
	- C:\Users\gamin\OneDrive\Documents\My Games\Skyrim Special Edition\Skyrim.ini
- Valid path on my system:
	- C:\Users\gamin\OneDrive\Documents\my games\Skyrim VR\Skyrim.ini
	- C:\Users\gamin\OneDrive\Documents\my games\Skyrim VR\SkyrimVR.ini
	- C:\Users\gamin\OneDrive\Documents\My Games\Skyrim Special Edition\

_edit1: Using Vortex mod manager._

_edit2: The errors go away if I simply create a blank Skyrim.ini file to make the target path, 'C:\Users\gamin\OneDrive\Documents\My Games\Skyrim Special Edition\Skyrim.ini', valid._

Exception stack trace/logs in attached file.
[ExceptionLog_SynthEBD_FileNotFoundSkyrimINI.txt](https://github.com/Synthesis-Collective/SynthEBD/files/9691099/ExceptionLog_SynthEBD_FileNotFoundSkyrimINI.txt)

**Comment by Piranha91** [comment]
Thanks for reporting this and especially posting the trace - it pointed me to the issue right away. I don't have an environment with only Skyrim VR installed (I do have VR but I also have SE so it's hard to test what happens if the SE files are missing). However, I changed all "hard" Skyrim SE references in the culprit file to get the currently set Skyrim version, so I think [0.8.3.2](https://github.com/Synthesis-Collective/SynthEBD/releases/tag/v0.8.3.2) should fix this.

**Comment by Piranha91** [comment]
Closed due to inactivity - feel free to reopen if needed.

**Comment by icarus342** [comment]
Finally had time to test. Established control environment by reverting my personal changes and reproduced the exception on the previous version. 0.8.3.3 did not produce the exception.

Thanks for taking the time to fix this!
