### ISSUE TITLE
Duplicated Asset Pack not being stored as a new file

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#68]
Hi again Piranha, 

While creating a new asset pack config file, I've come across a rather "treacherous" bug... It seems that when using the 'duplicate' button to clone a texture asset pack config file, the new config is not being stored to disk as a new file, it overwrites the original one instead :(

Fortunately, this one is easy to reproduce:
 - Select an asset pack to edit
 - Click Duplicate
 - Edit something, changing Name and Prefix for example
 - Click Save
 - Close and reopen SynthEBD

There is now only one Asset Pack, the original being overwritten by the duplicated one, which should have been stored to its own file.

**Comment by Piranha91** [comment]
Yikes! Thank you very much for catching this; I hope you didn't lose too much work. This will be an easy fix, and I'll definitely patch it in the next release.

**Comment by Piranha91** [comment]
Should be fixed in 0.8.5.

**Comment by leonardovcr** [comment]
Can't reproduce anymore... nice!
