### ISSUE TITLE
Warning Bodyslide messages with latest SynthEBD 0.8.5

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#69]
Hey Piranha, now I'm getting these warning messages right after loading a savegame:

![image](https://user-images.githubusercontent.com/13605450/208813688-fc5dcbc5-1479-4d0e-8f27-65b2710bfdc1.png)

Some of those NPCs do have specific assignments, while others should get them from Descriptor rules. The Bodyslides themselves actually seem to be loading fine. But I don't recall these messages appearing before... For the record, I've recently switched from AutoBody to OBody NG (its in-game menu seems to work better than AutoBody's) and from .ini to .json option in SynthEBD.

**Comment by Piranha91** [comment]
Unfortunately I didn't realize that the old headpart and bodyslide scripts would not be upgradeable in a current save. You'll probably need to either do a clean save without and then with SynthEBD, or else use fallrim tools to clean the SynthEBD scripts

**Comment by leonardovcr** [comment]
Got it, thanks!

**Comment by leonardovcr** [comment]
Hi Piranha, I'm reopening this issue since now I'm having a related annoyance...

First, those bodyslide assignment error messages only went away after I made a savegame without SynthEBD and OBody, and cleaned the save file with Resaver. So far so good.

However, now I'm getting constant Debug messages of the type "SynthEBD: Assigned bodyslide preset for...". for every NPC I meet. I've made sure to clean my SynthEBD output mod directory and disable the "Use Verbose Scripts" on Body Integration Misc Settings prior to running the patcher again.

I can vaguely remember running the patcher once with that option enabled sometime before. Maybe there's some garbage left somewhere?

**Comment by Piranha91** [comment]
Huh. In your current SynthEBD.esp, is this set to 0 or 1?

**Comment by leonardovcr** [comment]
Zero... :(

![image](https://user-images.githubusercontent.com/13605450/209420810-51aa703e-a6e5-4b14-be31-c2307fad2f54.png)

**Comment by Piranha91** [comment]
This might be easier? https://steamcommunity.com/app/72850/discussions/0/530646715637721881/

**Comment by leonardovcr** [comment]
> This might be easier? https://steamcommunity.com/app/72850/discussions/0/530646715637721881/

Yeah that actually was a lot easier lol

However, it changed nothing. I even tried waiting a bit to give time for the scripts to load, but as soon as I enter a new cell, those messages appear for every npc again...

**Comment by Piranha91** [comment]
Hmm. If you're on the SkyrimMods discord I'll post over there in the dev channel if you want to follow live. I'm still relatively new to Papyrus - sorry for the hiccups.

**Comment by Piranha91** [comment]
Think I found the problem - I'll send an updated script to try in a bit.

**Comment by leonardovcr** [comment]
> Hmm. If you're on the /r/SkyrimMods discord I'll post over there in the dev channel if you want to follow live. I'm still relatively new to Papyrus - sorry for the hiccups.

I saw your message there, but just to clarify, the game is loading with the value already set to 0. Tried 'show SynthEBD_BodyslideVerboseMode' right after loading the cleaned savegame, and it shows '0'.

Gotta sleep now, tomorrow I'll try your script. Thanks for your help, as always :)

**Comment by Piranha91** [comment]
Yeah the script is currently checking if the global exists instead of what its value is lol. Whoops.

**Comment by Piranha91** [comment]
Should be fixed in 0.8.6.2. Thanks for the report - not sure how this slipped by when testing. Guess I was more focused on the face sculpt issue.

**Comment by leonardovcr** [comment]
It's fixed now, thanks and merry christmas :)
