### ISSUE TITLE
Missing default Race Groupings for other races.

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#72]
Hi Piranha,

I've noticed that SynthEBD comes with some Race Groupings already included as default, like "HUMANOID PLAYABLE", "ELVEN", etc. Why not include default race groupings for each of the other races as well? 
For their Race/Vampire pairing, there's only ELDER, KHAJIIT and ARGONIAN already included. We are missing the following Race/Vampire groupings:

NORD (with DLC1NordRace included as well)
BRETON
REDGUARD
IMPERIAL
ORC
HIGHELF
SNOWELF (this one without its vampire equivalent since that doesn't seem to exist on vanilla)
DARKELF
WOODELF

I've created those custom race groupings above in my own installation, and use them on my asset pack config files. However, I fear that when those confs are shared to others, those rules won't work, since other people's environment won't have those basic groupings created by default... 

What do you think?

**Comment by Piranha91** [comment]
I’ve actually considered adding those and never prioritized it. I can add them, but I actually think the better solution would be for race groupings to behave like attribute groups where if the main settings are missing a grouping it’s supplied by the config file “locally”.

**Comment by leonardovcr** [comment]
That could work too, I've seen that behaviour when using your ALT2 pack and when I export my own custom ones. But those groupings I quoted should be default in SynthEBD since they are kind of basic race groupings for the vanilla game, while your solution would be better suited for creating asset packs with more custom stuff, like custom race groupings for example.

**Comment by Piranha91** [comment]
Done in 0.9 (the groupings are created when the patcher first launches, so if you already have groupings defined it won't know to regenerate them). If you want to try them out you can delete the generalsettings.json file, or open it with a text editor and delete the entire "RaceGroupings": [...] section.

**Comment by leonardovcr** [comment]
Nice, thanks! On another opportunity, some custom general purpose attribute groups could also be considered to be shipped as default in synthebd , like female/male age40, age50, freckle groups, etc. Those would come in handy for creating most texture packs out there.

**Comment by leonardovcr** [comment]
Hey Piranha, had to reopen this issue for a quick report. I'm testing those groups now, and looks like Nord group has "NordRaceAstrid" instead of "DLC1NordRace". This could lead to some problems like charred Astrid getting smooth skin :P

**Comment by Piranha91** [comment]
Thanks, fixed in 0.9.1.2.

**Comment by leonardovcr** [comment]
Thanks!
