### ISSUE TITLE
Can't remove Attribute from Attribute Group

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#75]
Hi Piranha, here's a quick UI bug I've come across:

![image](https://user-images.githubusercontent.com/13605450/211674144-d62eb5ff-2531-4882-ad0a-218772e8cdf3.png)

After removing a sub-attribute, there's no way to reach the Remove Attribute button since the Test Attribute button overlaps it. Resizing windows has no effect, so one must remove the entire attribute group and create another.

**Comment by Piranha91** [comment]
Thanks, will fix in the next release! Hopefully before end of week.

**Comment by Piranha91** [comment]
I'm actually having some trouble replicating this. Can you give me a step-by-step of how you trigger it?

https://i.imgur.com/UShMjIe.gif

**Comment by leonardovcr** [comment]
Strangely enough, I can't seem to replicate it also in a new synthebd session... I wonder if it has something to do with long editing sessions or memory leak 🤔 

Anyway, let's leave the issue open until I or someone else manages to accurately reproduce it again. That was the second time it happened to me.

**Comment by leonardovcr** [comment]
Managed to record since it has happened again: https://imgur.com/a/t7cUTO2

It 'just happens' after a long time of editing I think. So far, it hasn't happened between short sessions of synthebd rule editing.

**Comment by leonardovcr** [comment]
Whew, found out how to reproduce it: https://imgur.com/a/VxofkDL

**Comment by Piranha91** [comment]
Thanks, was able to reproduce. Should be fixed in 0.9.1

**Comment by leonardovcr** [comment]
Fixed, thanks!

**Comment by leonardovcr** [comment]
Hey Piranha, had to reopen this issue since I've come across it again, but this time on an attr group of a body descriptor:

![image](https://user-images.githubusercontent.com/13605450/220976993-77871302-d82a-49c5-942b-a715a2619589.png)

That descriptor was imported with empty allowed npc attr. rules, and bugged like that after I tried to remove it. On the exported bodyslide file, the descriptor looks like this:

```
    {
      "ID": {
        "Category": "Build",
        "Value": "Curvy"
      },
      "AssociatedRules": {
        "AllowedRaces": [],
        "DisallowedRaces": [],
        "AllowedRaceGroupings": [],
        "DisallowedRaceGroupings": [],
        "AllowedAttributes": [
          {
            "SubAttributes": [
              {
                "SelectedLabels": [
                  "Immersive Wenches"
                ],
                "Type": "Group",
                "ForceMode": "ForceIf",
                "Weighting": 1
              }
            ]
          }
        ],
        "DisallowedAttributes": [],
        "AllowUnique": true,
        "AllowNonUnique": true,
        "AllowRandom": true,
        "ProbabilityWeighting": 3.0,
        "WeightRange": {
          "Lower": 0,
          "Upper": 100
        }
      }
    },
```

I'm testing this bodyslide importing on a brand new v0.9.6.3 installation, so there is no Immersive Wenches attr group already created (which references npcs from another mod). That's probably why it got imported with empty rules.

**Comment by Piranha91** [comment]
Is this still an active issue?

**Comment by leonardovcr** [comment]
I think not, with latest version, I tried using a .json with an empty attr group on the body descriptor, and was able to remove it just fine. Couldn't test with the bodyslide importing feature, since it seems to be broken for now :(

**Comment by leonardovcr** [comment]
Tested on 0.9.8.2, doesn't happen anymore :) Closing issue.
