### ISSUE TITLE
Too many "Circular reference detected" messages while launching SynthEBD

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#76]
Hi again,

I've been messing around with attribute groups now, and made the mistake of creating some circular references. While restarting SynthEBD, there's a lot of "Circular reference detected" messages while launching, forcing the user to click in the popup window each time a message appear. I think I did some good 20-30 clicks until the app launched. One message shouldn't be enough? 👍

**Comment by Piranha91** [comment]
Did you make the attribute groups outside of the UI? The UI is supposed to check every time you click a group box and immediately undo it if it sees a circular ref. It sounds like it was loading in the config and every time it found one, it tried to check the box, detected the circular ref, and backtracked it. It shouldn’t allow you to make any circular refs from the UI at all - if it did, something broke in one of the recent updates. Aternatively if you were editing the json in a text editor then yeah, it’ll flag every circular ref that it finds as it’s loading in.

**Comment by leonardovcr** [comment]
Nope, I've only used the UI to create Attribute Groups in General Settings section. While editing, I didn't get any messages about Circular References.

Off the top of my head, I did the following:

Created Group1 with some rules.
Created Group2 and added other rules and also included Group1
Created Group3 and added some other rules and included Group2

Even reverting those changes didn't solve the problem... Still trying to pinpoint the specific circular reference, which I can't seem to find... it would be nice to make synthebd print the offending rule or conf to ease debugging 👍

**Comment by Piranha91** [comment]
Yep, can definitely make that happen. Real time warning must have broken at some point - sorry about that. Will do some investigating.

**Comment by leonardovcr** [comment]
Should that really trigger a circular reference? 

I mean, considering the example above, a circular reference should only trigger if I also had Group3 being included in Group1/Group2, or if Group2 were to be included in Group1/Group3.

Thanks for investigating!

**Comment by Piranha91** [comment]
Should be fixed in 0.9; let me know if it still gives you issues and we can troubleshoot further.

**Comment by leonardovcr** [comment]
Okay, tested a little bit more and UI now warns when the user attempts to create a circular reference... however, looks like there are still some issues with the rules applying 😓  

Here's what I tried:

Created 3 Atribt. Groups:
 - Mature Women
 - Female Age 40
 - Female Age 50

For the first, I've included those last two:
![image](https://user-images.githubusercontent.com/13605450/215290820-cb1b3dc5-ec34-439f-9d5a-7579161b8fb4.png)

And for each Age group I've included their respective FaceTextures:
![image](https://user-images.githubusercontent.com/13605450/215290844-a636727b-bdaa-4f7f-9cab-a52511f5e12b.png)

For an asset pack's head details, patcher seems to correctly identify when those last two groups are assigned independently, like here:

![image](https://user-images.githubusercontent.com/13605450/215290921-fa9c93d4-506e-4380-8adb-4418d49998d0.png)

However, the patcher doesn't match any NPC (for example, Colette which has age 40 face textures) when there are rules with the attribute group "Mature Women", as configured in the first screenshot. The patcher does match, however, if I set the group like this:

![image](https://user-images.githubusercontent.com/13605450/215291161-902e910b-f400-4e39-b464-367f687fe6ba.png)

Looks like an AND/OR issue in the code, I think...

**Comment by Piranha91** [comment]
Yep, good catch. This was indeed an OR logic issue. Thanks!

**Comment by leonardovcr** [comment]
Seems to be fixed now, thanks!
