### ISSUE TITLE
Asset Pack's Attribute Groups not being replaced by General Attribute Groups

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#77]
Hey Piranha,

Here's another behaviour I'm running into, which I don't think is intended behaviour... 

I'm trying to centralise my Attribute Groups rule management by editing them only in the General Settings screen. I was under the impression that by doing that, an Asset Pack's Attr Groups would be instantly overwritten whenever I switch screens, but it seems that does not happen. 

From what I could test, an asset pack's attribute group is only properly superceded if I restart SynthEBD, and even then, only if that asset pack's attr group list is empty, . If it is not empy, general groups are added, but the asset's attr groups which share the same name are not overwritten by the ones from general settings. This happens with attr groups configured in O/AutoBody Integration screen too.

So, the only way I've managed to centralise configuration, and have them being assigned to all asset packs/obody integration, is to manually remove all of an asset pack's attr group, on obody integration screen, and restart synthebd. The problem with this approach is that all the attr groups references configured in the asset pack's rules are lost :/

**Comment by Piranha91** [comment]
The purpose of this functionality is not actually to replace the attribute groups in the UI. It simply substitutes which group definition is used when running the patcher. For example, say you have an attribute group called “Can be dirty” to which you’ve added Beggar class and Miner class. Now a user downloads your config file, but in their general settings, they also have a “Can be dirty” group which includes Beggar, Miner, and Lumberjack. If they have the overwrite toggle checked, the patcher will use their attribute group definition including lumberjack. If it’s not checked, the patcher will use the definition included with the config file (no lumberjack). But the definitions in the config file will not change - this simply changes which source the patcher reads them from during execution.

**Comment by leonardovcr** [comment]
Ah... I see. I've just did a quick patch run and it behaves just as you explained.. thanks!
