### ISSUE TITLE
Race alias double tick

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#79]
So, this time I actually didn't forget to record a bug 😄 

https://imgur.com/a/h4FigaQ

Pretty self-explanatory. Ticking one of those last two options automatically checks the other too.

**Comment by Piranha91** [comment]
Whoops! Bad autocomplete by Visual Studio I think :). One-liner fix on my end; it'll be included in the next release. Thanks!

**Comment by Piranha91** [comment]
Should be fixed in 0.9

**Comment by leonardovcr** [comment]
Seems to be ok now 👍
