### ISSUE TITLE
I cannot scroll in BODY DISCRIPTION & ATTRIBUTE GROUPES. and more

### ISSUE THREAD

**Issue by Daikichi-Takahey** [Synthesis-Collective/SynthEBD#8]
Thanks for your work.
I am happy that the textures and meshes are set up the way I want them.
But while setting it up I found some problems. As usual please take a look at the images. Thanks
![スクリーンショット (22)](https://user-images.githubusercontent.com/100354903/159216214-5c0afc5e-aea4-4b27-9990-962888fc6f10.png)
![スクリーンショット (23)](https://user-images.githubusercontent.com/100354903/159216990-d1313adc-6f2f-488f-b596-312097b950b9.png)

**Comment by Piranha91** [comment]
Thank you for the diligent bug hunting. Both scrolling and ForceIf weighting display should be fixed in 0.5.1.
