### ISSUE TITLE
Can't access Skyrim.esm's texture on SynthEBD 0.9.0

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#81]
Hey Piranha, thanks for newest release. Will check those issues when I find some time today.

Did try a quick patcher run now, but I'm having trouble starting the patcher using Demoniac asset pack:

Errors detected in Config File Demoniac 2K CBBE
Subgroup HDE.BDM:BlankDetailMap within branch 5
No file exists at C:\program files (x86)\steam\steamapps\common\Skyrim Special Edition\Data\Skyrim.esm\Textures\actors\character\male\blankdetailmap.dds

Of coure, file exists... did something change? I'm running SynthEBD standalone (not through synthesis).

**Comment by Piranha91** [comment]
Whoops! Looks like there was a small change in Mutagen that I didn't notice, and I didn't have Demoniac installed during testing so the UI was never looking into BSAs. Should be fixed in my 0.9.0.1. Sorry about that.

**Comment by leonardovcr** [comment]
Solved, thanks!
