### ISSUE TITLE
New UI bug on Attribute

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#82]
Hey Piranha, looks like a new UI bug was introduced:

https://imgur.com/a/L5kqle4

Group and FaceTexture attributes *sometimes* lead to the same window now. Pretty weird. 

I've also noticed that the Attribute Groups window does not stretch as wide anymore. Only if I first activate Linked NPC Groups windows (which is quite wide by default) and then activate the others without closing the first...

**Comment by Piranha91** [comment]
I actually ran into this a couple weeks ago, couldn't figure out the problem, and forgot about it. Thanks for finding it and reminding me - I was able to track it down this time around. Also fixed the UI stretch.

**Comment by leonardovcr** [comment]
Both issues fixed now, thanks!
