### ISSUE TITLE
Config installer incompatible with .rar files?

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#88]
Hey Piranha, I'm building a custom config file to test those new Mix In features, and stumbled across a problem where the config installer doesn't seem to work when a texture mod is packaged as a rar file. If I unpack and compress as a .7z, then installer runs fine.

Here's the installer I'm working on:

[Custom.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10505472/Custom.zip)

Also, on another note, I might be missing something here. but, is it possible to have a custom "ConfigPrefix" per Download file? 

The reason for that is because I'm trying to create one Asset Pack for all of [s4rMs](https://www.nexusmods.com/skyrimspecialedition/users/108820633)'s normal map mods, but most files in the mod's packages ('softie' mod and 'toned' mod for example) share the same path in relation to the package root path. I fear the installer would end up overwriting them when building the Asset Pack mod directory...

**Comment by Piranha91** [comment]
I went ahead and uploaded a release that should support .rar to unblock you from working on the config file. Having a custom ConfigPrefix is going to require a fairly extensive rework of the installer, because it's pretty much built around having one prefix per config file.

**Comment by leonardovcr** [comment]
Thanks, I wasn't aware of that! Wish I had known before making all those installer files by hand 😄

**Comment by leonardovcr** [comment]
Just tested with .rar files, and installer is fine now, thanks 👍

**Comment by Piranha91** [comment]
I implemented the requested prefix-per-download pattern in 0.9.2. I believe it should do what you requested. It works like this. Say you have two mods that both extract to the same path:

A: 
![image](https://user-images.githubusercontent.com/63175798/215318963-988b5867-34ee-4d43-8c01-a89d93fd920b.png)

B:
![image](https://user-images.githubusercontent.com/63175798/215318974-07b314ea-a557-45ad-910e-c7345b80f23d.png)

In your config file, you give one file a unique prefix (in this case, "prefixA"):
![image](https://user-images.githubusercontent.com/63175798/215319045-d11f2c00-af9d-4739-a56b-b5317a4d6633.png)

And the other file a different prefix (in this case, "prefixB"):
![image](https://user-images.githubusercontent.com/63175798/215319069-482151df-c092-4871-9255-24a9c14298c5.png)

Then, when packaging your manifest, you give the same prefixes to the corresponding downloadInfos:
![image](https://user-images.githubusercontent.com/63175798/215319131-704d144f-1801-4779-b996-8cc7d52c72ce.png)

The installer should now be able to place the assets correctly.

**Comment by leonardovcr** [comment]
Nice, along with .rar support, this should cover most Nexus download scenarios now, thanks!
