### ISSUE TITLE
Can't scroll down Race Groupings list

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#89]
Hey Piranha, just a quick UI issue before I forget:

![image](https://user-images.githubusercontent.com/13605450/215129281-f4639861-2221-4799-a340-4b3cc4d80a44.png)

When there's too many race groupings, there's no way to scroll down an asset pack's race grouping list. There's no problem navigating race groupings on General Settings though.

**Comment by Piranha91** [comment]
Fixed in 0.9.2.

**Comment by leonardovcr** [comment]
Thanks!
