### ISSUE TITLE
Creating a new asset pack config file does not properly assign DefaultRecordTemplate

### ISSUE THREAD

**Issue by Tycoonman500** [Synthesis-Collective/SynthEBD#9]
Creating a new config file from the application creates a json with "DefaultRecordTemplate" set to "Null", resulting in record intellisense not functioning for the config.

**Comment by Piranha91** [comment]
Apologies for the delay, this month has been crazy for me. I have fixed the issue on my end, hoping to upload a new version later this week containing this fix and others. Will close this issue when I do. Thank you for submitting the report.

**Comment by Piranha91** [comment]
Fixed in 0.6. Thanks again for reporting!
