### ISSUE TITLE
Two little invalid character bugs

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#90]
Hi Piranha, two more little ones:

 - Having an underscore "_" on a subgroup's ID does not allow the patcher to start, however, validate button does not catch this error, and says config file is valid.
 - Verbose NPC log doesn't work for NPCs which have quotations marks ( "" ) on its name. Since npc log filenames have an npc's name appended to them, the patcher fails while trying to create the file due to invalid character for a filename.

**Comment by Piranha91** [comment]
Are you sure about the first one? This is what I get when I try to validate your custom.zip that you uploaded in another issue: 
![image](https://user-images.githubusercontent.com/63175798/215249010-3c31e709-5e3d-4fbb-8e86-88f61cdc9dcd.png)

**Comment by leonardovcr** [comment]
Yeah, sorry about that. I wonder if I had the problematic asset pack disabled while pushing the Validate button...

**Comment by Piranha91** [comment]
Seems likely ;). First issue should be fixed in 0.9.2

**Comment by leonardovcr** [comment]
Thanks!
