### ISSUE TITLE
Strange behaviour on Specific NPC Assignments

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#94]
Hey Piranha, sorry to bother again with yet another issue... 😅 but this is quite an 'esoteric' bug 🤔 

Right after launching SynthEBD and clicking on Specific NPC Assignments, there's a long pause, and when it finishes, the first NPC of the list is replaced with another from somewhere around the middle of the list:

https://imgur.com/a/YX1EKmh

I think it is the same or at least very similar to the problem I reported on issue #64 back in december. I've recently made some changes to my load order, so maybe it's an issue with NPC FormKeys? I'm at a loss here of what might be causing this...

Here's the .json:
[Specific NPC Assignments.zip](https://github.com/Synthesis-Collective/SynthEBD/files/10541099/Specific.NPC.Assignments.zip)

**Comment by Piranha91** [comment]
I'm having trouble replicating, probably because most of your mods are missing in my load order. I have some idea of where to start but waiting to implement pending getting some advice on Discord. Will try to fix in 0.9.3.1.

**Comment by Piranha91** [comment]
Closed due to inactivity - let me know if this needs to be reopened.
