### ISSUE TITLE
Not an issue, just a suggestion

### ISSUE THREAD

**Issue by roysorlie** [Synthesis-Collective/SynthEBD#95]
Hello again :)

You may already have thought about this, but in case you hadn't..

Would it not be possible to create asset packs and distribute character specific DAR animations through SynthEBD?
While I quite enjoy the distribution features of DAR, I prefer a curated set for specific NPC's, and SynthEBD seems like a great tool for just such a purpose.

Cheers

**Comment by Piranha91** [comment]
My understanding is that DAR doesn't replace any existing asset animations, right? It just writes an ini file for the DAR plugin/dll to read? If so, it's probably beyond the scope of what SynthEBD is trying to accomplish. That said, I've often thought that SynthEBD's attribute matching code could be useful for other patchers, and it's freely available. I don't have the bandwidth to make additional patchers at the moment, but if you or someone else wants to take a crack at it I could help with getting the attribute code integrated.

**Comment by roysorlie** [comment]
You're right it doesn't replace assets, but it does create a unique folder structure an dwrites a simple .ini withing the structure.
The basic folder structure is set up like base animations, but they will refer to a specific baseID within a a folder named for the .esp/.esm the unique NPC the NPC is first introduced.

It was the automation of setting up an asset pack of animations, and applying some or all variants of an idle to a specific NPC with a simple .ini generation within the generated folder structure.

I fully understand you have your hands full already. I'll let you know if I feel particularly adventureous and want to take a crack at it :)

Cheers
