### ISSUE TITLE
Specific NPC assignments inconsistencies

### ISSUE THREAD

**Issue by leonardovcr** [Synthesis-Collective/SynthEBD#96]
Hey Piranha, while checking verbose logs for some npcs, I've found these issues, all related to the specific npc assignments menu:

 - There's no logging for head parts while using specific npc assignments to set, for example, a forced hair.
 - Any forced MixIn is ignored, in any order, if they are set on specific npc assignments. Forced asset pack, height and bodyslide however, are ok. Not sure about forced head parts due to logging issue above.

Also, about forced MixIn and specific npc assignments, is there a way to set a forced MixIn order for each npc, or they only follow the distribution order set on Textures and Meshes menu?

**Comment by Piranha91** [comment]
I'll look into the mixins - are you sure about the first one though? Here's what my log looks like when forcing hair:
![image](https://user-images.githubusercontent.com/63175798/216849809-96bed69b-e54f-4cb1-aaa3-e1a2e3552566.png)

**Comment by leonardovcr** [comment]
Yeah, pretty sure... What I'm finding really weird is that my the log for the specific NPC doesn't even mention the HeadParts section:

![image](https://user-images.githubusercontent.com/13605450/216850846-a1f04974-8c30-46c7-9a0b-8d01379a3e99.png)

Here's how it's set:

![image](https://user-images.githubusercontent.com/13605450/216850877-a28e0fec-c621-43b7-a823-4f4338b77958.png)

Maybe this might be related to how I've setup head parts distribution?

![image](https://user-images.githubusercontent.com/13605450/216851170-4d2cbe40-554a-48db-b23f-d5b48168a499.png)

The NPC in question is not a member of the Immersive Wenches group. But I think it shouldn't matter since specific npc assignments should override everything, I think. 🤔 

All NPCs from Immersive Wenches have their headparts distribution reported in the logs just fine.

**Comment by leonardovcr** [comment]
Ooops, I think I found out why... I've missed this line in the log file:

**Head part assignment is blocked for current NPC because it might have custom FaceGen**

😟

**Comment by Piranha91** [comment]
You can toggle that behavior here: 
![image](https://user-images.githubusercontent.com/63175798/216852254-a53828f5-2830-450c-8219-dd65cfe49311.png)

BTW, have you been noticing the issue that focustense and I were discussing a few weeks ago [here](https://discord.com/channels/759302581448474626/759344198792380416/1066245687743873084)? I'm curious about people's experience with the headpart distributor - I never use it myself; only "resurrected" it from EBD SSE due to user request. Has this been happening for you?

**Comment by leonardovcr** [comment]
Oh thanks, totally missed that toggle 🤦 

Humm, I think my experience won't be of much use since I'm also not a heavy user of headparts distribution. I'm only now trying to learn it because there are some mods (like captives.esp) that have npcs with very ugly and boisterous hair, and I want to swap them for vanilla ones. 
So far, I have only one NPC whom I'm forcing a specific hair, and I still haven't played enough to find her in-game 😆 The ones I did find in-game (from captives.esp), I haven't interacted much and didn't notice any problem, but I guess that's because they don't have custom face sculpts since I don't get that custom FaceGen message on their logs (they do have custom .nif files on FaceGenData\FaceGeom\Captives.esp though).

**Comment by Piranha91** [comment]
Issue #2 should be fixed in 0.9.4.1. Let me know if you now see the intended behavior.

Regarding custom per-NPC config ordering, currently not possible but shouldn't be hard to implement. I can probably do it this week if you'd find it useful.

**Comment by leonardovcr** [comment]
Thanks Piranha, looks like mix-ins are being properly assigned now. I think ordering shouldn't be needed, as least I still haven't thought of a good use case for that. I am however, trying to figure out what should be the default behaviour for Mix-Ins when using specific npc assignments... as in, if none are chosen, should the patcher ignore them, or run them all according to distribution order and probabilities?

My rationale is that some mix-ins are intended to be always on (like those with 100% probability of distribution), so having to manually enable them for each npc would be a chore. However, others aren't meant to be always used (like those with 25/50% probability), and so, having to disable them on a lot of npcs would be equally tedious.

I was thinking of having mix-ins distribution on by default, but also having a toggle on a mix-in config distribution rules, to set its default engagement (on or off by default) during specific npc assignemnts... what do you think?

**Comment by Piranha91** [comment]
The way it works now (or should work, anyway), is:

If a mix-in is chosen in the Specific Assignments menu, and the Decline checkbox (new in the last update) is unchecked, it 100% gets assigned.

If the Decline checkbox is checked, it is 100% not assigned.

If it’s not selected in Specific NPC Assignments, it gets distributed according to its probability.

This seems like the simplest logic - given this, do you think a toggle is required? Would it be useful to add a button that says “for all Specific Assignments that include me, check/uncheck the Decline button”?

**Comment by leonardovcr** [comment]
I think a better toggle would be "for all specific assignments where I'm not chosen, leave me out of the distribution, unless I'm explicitly chosen" or "for all Specific Assignments that do not include me, check/uncheck the decline button". Am I making sense? 😄

**Comment by Piranha91** [comment]
If I understand correctly, the first one could be rephrased as “for all specific NPC assignments that do not include me, add me and (check/uncheck) the Decline button”. Yes?

The second one I think is a logical contradiction- if a specific NPC assignment doesn’t include a given mix in, then there is no Decline button to check/uncheck.


Do I understand variant 1 correctly, and is it suitable?

**Comment by leonardovcr** [comment]
Yeah, your understanding of the first one is spot on,  and will work just fine for the scenarios I had in mind. It gives us better control over the default distribution behaviour.

**Comment by Piranha91** [comment]
Cool, should be able to add that in. I also preemptively started coding the specific assignment asset ordering menu, so that should also be in the next update.

**Comment by Piranha91** [comment]
Alright, up in 0.9.4.2.

**Comment by leonardovcr** [comment]
Thanks Piranha, I'm doing a quick test now, and here are some issues I've found:

 - Distribution order is not saved when changing versions. By changing versions I mean unpacking the new zip and copying over the "settings" folder from the old version.
 - Do all specific npc assignments inherit the default distribution order by default? If so, that's fine, but the problem now is that the distribution order for all of them are wrong, due to the issue related above. Maybe another button to override distribution order?

**Comment by Piranha91** [comment]
Huh that's weird - did you lose all TexMesh settings from the previous version, or specifically the distribution order? Either way that's strange because nothing about the asset order changed from .1 to .2. I'll look into that tonight.

**Comment by Piranha91** [comment]
Strange. I just tried downloading 0.9.4.2, setting a custom distribution order, downloading 0.9.4.3 and overwriting the previous installation, and the order was preserved. Were you by chance deleting your Settings folder as you upgraded? I'm assuming not, because that would also delete all of your OBody annotations and you would have noticed earlier... not sure why that would be happening otherwise though, because the order lives in Settings\TexMeshSettings.json and the SynthEBD.7z archive doesn't contain a Settings folder. 

Anyway, added the requested buttons in 0.9.4.3 (and then a minor fix to 0.9.4.4); hope this helps you fix your assignments quickly.

**Comment by leonardovcr** [comment]
Just checking the new version, and those buttons fixed all my npcs ordering :) Thanks a lot, really handy.

Now, following the same upgrade procedure, this time I tested by copying my Settings folder from an old SynthEBD_v0.9.4.0 version to a new folder with latest version, and Distribution Order was kept on Textures and Meshes tab! However, npcs from specific npc assignments didn't inherit that order, they loaded with Primary First followed by Mix-Ins. But now it doesn't matter much since we have buttons to fix that easily 👍

**Comment by leonardovcr** [comment]
Actually, scratch that. Tested again three times now, and order is being kept both in textures and meshes, and in specific npc assignments now. My eyes were deceiving me I think 🤦
